import test from "node:test";
import assert from "node:assert/strict";
import fs from "fs/promises";
import os from "os";
import path from "path";

async function loadCloudState(name,fetchImpl){const root=await fs.mkdtemp(path.join(os.tmpdir(),`georgie-cloud-${name}-`));process.env.GEORGIE_SUPABASE_URL="https://example.supabase.co";process.env.GEORGIE_SUPABASE_SERVICE_ROLE_KEY="server-only-test-key";process.env.GEORGIE_DATA_DIR=root;process.env.GEORGIE_CLOUD_STATE_TIMEOUT_MS="250";process.env.GEORGIE_CLOUD_STATE_MAX_ATTEMPTS="3";process.env.GEORGIE_CLOUD_STATE_RETRY_BASE_MS="0";global.fetch=fetchImpl;const module=await import(`../src/cloud-state.js?test=${name}-${Date.now()}`);return {module,root};}
function response(value,status=200){return {ok:status>=200&&status<300,status,json:async()=>value};}

test("cloud state retries a transient timeout and recovers",async()=>{let calls=0;const {module}=await loadCloudState("retry",async()=>{calls+=1;if(calls===1){const error=new Error("temporary timeout");error.name="TimeoutError";throw error;}return response({tasks:["kept"]});});assert.deepEqual(await module.readCloudState("u1","tasks",{tasks:[]}),{tasks:["kept"]});assert.equal(calls,2);assert.equal(module.cloudStateStatus().healthy,true);});
test("concurrent reads for one namespace share one cloud request",async()=>{let calls=0;const {module}=await loadCloudState("coalesce",async()=>{calls+=1;await new Promise(resolve=>setTimeout(resolve,20));return response({value:7});});const [a,b,c]=await Promise.all([module.readCloudState("u1","same",{}),module.readCloudState("u1","same",{}),module.readCloudState("u1","same",{})]);assert.deepEqual([a,b,c],[{value:7},{value:7},{value:7}]);assert.equal(calls,1);});
test("failed cloud write remains durable locally and is recovered",async()=>{let available=false;const {module}=await loadCloudState("outbox",async()=>{if(!available)throw new TypeError("network unavailable");return response(true);});assert.equal(await module.writeCloudState("u1","tasks",{tasks:["georgie"]}),true);assert.equal(module.cloudStateStatus().degraded,true);assert.ok(module.cloudStateStatus().pendingWrites>=1);available=true;const result=await module.recoverCloudStateWrites();assert.equal(result.recovered,1);assert.equal(result.remaining,0);assert.equal(module.cloudStateStatus().healthy,true);});
test("read timeout returns the last durable mirror instead of empty fallback",async()=>{let available=true;const {module}=await loadCloudState("mirror",async()=>{if(!available)throw new TypeError("network unavailable");return response(true);});await module.writeCloudState("u1","tasks",{tasks:["preserved"]});available=false;assert.deepEqual(await module.readCloudState("u1","tasks",{tasks:[]}),{tasks:["preserved"]});assert.equal(module.cloudStateStatus().degraded,true);});
test("writes to one namespace are serialized in request order",async()=>{let active=0,maxActive=0;const bodies=[];const {module}=await loadCloudState("ordered",async(_url,options)=>{active+=1;maxActive=Math.max(maxActive,active);bodies.push(JSON.parse(options.body).p_state);await new Promise(resolve=>setTimeout(resolve,15));active-=1;return response(true);});await Promise.all([module.writeCloudState("u1","tasks",{version:1}),module.writeCloudState("u1","tasks",{version:2})]);assert.equal(maxActive,1);assert.deepEqual(bodies,[{version:1},{version:2}]);});
