import test from "node:test";
import assert from "node:assert/strict";
import fs from "fs/promises";
import os from "os";
import path from "path";

async function loadCloudState(name,fetchImpl){const root=await fs.mkdtemp(path.join(os.tmpdir(),`georgie-cloud-${name}-`));process.env.GEORGIE_SUPABASE_URL="https://example.supabase.co";process.env.GEORGIE_SUPABASE_SERVICE_ROLE_KEY="server-only-test-key";process.env.GEORGIE_DATA_DIR=root;process.env.GEORGIE_CLOUD_STATE_TIMEOUT_MS="250";process.env.GEORGIE_CLOUD_STATE_MAX_ATTEMPTS="3";process.env.GEORGIE_CLOUD_STATE_RETRY_BASE_MS="0";process.env.GEORGIE_CLOUD_STATE_PROVIDER_COOLDOWN_MS="5000";process.env.GEORGIE_CLOUD_STATE_READ_CACHE_TTL_MS="100";global.fetch=fetchImpl;const module=await import(`../src/cloud-state.js?test=${name}-${Date.now()}`);return {module,root};}
function response(value,status=200){return {ok:status>=200&&status<300,status,json:async()=>value};}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));

test("foreground cloud state performs only one bounded attempt",async()=>{let calls=0;const {module}=await loadCloudState("retry",async()=>{calls+=1;const error=new Error("temporary timeout");error.name="TimeoutError";throw error;});assert.deepEqual(await module.readCloudState("u1","tasks",{tasks:[]}),{tasks:[]});assert.equal(calls,1);assert.equal(module.cloudStateStatus().foregroundAttempts,1);assert.equal(module.cloudStateStatus().degraded,true);});
test("a provider delay cannot multiply into a 36-second foreground stall",async()=>{let calls=0;const {module}=await loadCloudState("bounded-delay",async(_url,{signal})=>{calls+=1;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>resolve(response({late:true})),36_000);signal.addEventListener("abort",()=>{clearTimeout(timer);const error=new Error("aborted");error.name="AbortError";reject(error);},{once:true});});});const started=Date.now();assert.deepEqual(await module.readCloudState("u1","slow",{safe:true}),{safe:true});assert.ok(Date.now()-started<1000);assert.equal(calls,1);});
test("concurrent reads for one namespace share one cloud request",async()=>{let calls=0;const {module}=await loadCloudState("coalesce",async()=>{calls+=1;await wait(20);return response({value:7});});const [a,b,c]=await Promise.all([module.readCloudState("u1","same",{}),module.readCloudState("u1","same",{}),module.readCloudState("u1","same",{})]);assert.deepEqual([a,b,c],[{value:7},{value:7},{value:7}]);assert.equal(calls,1);});
test("near-sequential reads use a bounded read-through cache instead of hammering provider state",async()=>{let calls=0;const {module}=await loadCloudState("read-cache",async()=>{calls+=1;return response({value:9});});assert.deepEqual(await module.readCloudState("u1","same",{}),{value:9});assert.deepEqual(await module.readCloudState("u1","same",{}),{value:9});assert.deepEqual(await module.readCloudState("u1","same",{}),{value:9});assert.equal(calls,1);assert.equal(module.cloudStateStatus().readCacheTtlMs,100);await wait(120);assert.deepEqual(await module.readCloudState("u1","same",{}),{value:9});assert.equal(calls,2);});
test("failed cloud write remains durable locally and is recovered",async()=>{let available=false;const {module}=await loadCloudState("outbox",async()=>{if(!available)throw new TypeError("network unavailable");return response(true);});assert.equal(await module.writeCloudState("u1","tasks",{tasks:["georgie"]}),true);assert.equal(module.cloudStateStatus().degraded,true);assert.ok(module.cloudStateStatus().pendingWrites>=1);available=true;const result=await module.recoverCloudStateWrites();assert.equal(result.recovered,1);assert.equal(result.remaining,0);assert.equal(module.cloudStateStatus().healthy,true);});
test("read timeout returns the last durable mirror instead of empty fallback",async()=>{let available=true;const {module}=await loadCloudState("mirror",async()=>{if(!available)throw new TypeError("network unavailable");return response(true);});await module.writeCloudState("u1","tasks",{tasks:["preserved"]});await wait(120);available=false;assert.deepEqual(await module.readCloudState("u1","tasks",{tasks:[]}),{tasks:["preserved"]});assert.equal(module.cloudStateStatus().degraded,true);});
test("identical clean writes are suppressed while changed writes remain serialized and durable",async()=>{let calls=0;const bodies=[];const {module}=await loadCloudState("write-dedupe",async(_url,options)=>{calls+=1;bodies.push(JSON.parse(options.body).p_state);return response(true);});assert.equal(await module.writeCloudState("u1","tasks",{version:1}),true);assert.equal(await module.writeCloudState("u1","tasks",{version:1}),true);assert.equal(calls,1);assert.deepEqual(bodies,[{version:1}]);assert.equal(module.cloudStateStatus().identicalCleanWritesSuppressed,true);assert.equal(await module.writeCloudState("u1","tasks",{version:2}),true);assert.equal(calls,2);assert.deepEqual(bodies,[{version:1},{version:2}]);});
test("writes to one namespace are serialized in request order",async()=>{let active=0,maxActive=0;const bodies=[];const {module}=await loadCloudState("ordered",async(_url,options)=>{active+=1;maxActive=Math.max(maxActive,active);bodies.push(JSON.parse(options.body).p_state);await wait(15);active-=1;return response(true);});await Promise.all([module.writeCloudState("u1","tasks",{version:1}),module.writeCloudState("u1","tasks",{version:2})]);assert.equal(maxActive,1);assert.deepEqual(bodies,[{version:1},{version:2}]);});
test("a dirty local mirror returns immediately while recovery stays off the foreground path",async()=>{let available=false,calls=0;const {module}=await loadCloudState("dirty-nonblocking",async()=>{calls+=1;if(!available)throw new TypeError("network unavailable");return response(true);});await module.writeCloudState("u1","tasks",{tasks:["preserved"]});const before=calls,started=Date.now();assert.deepEqual(await module.readCloudState("u1","tasks",{tasks:[]}),{tasks:["preserved"]});assert.ok(Date.now()-started<100);assert.equal(module.cloudStateStatus().dirtyMirrorReadsBlockForeground,false);assert.ok(calls>=before);});
test("one provider failure opens a global circuit for unrelated namespaces",async()=>{let calls=0;const {module}=await loadCloudState("global-circuit",async()=>{calls+=1;throw new TypeError("provider unavailable");});assert.deepEqual(await module.readCloudState("u1","tasks",{tasks:[]}),{tasks:[]});assert.equal(module.cloudStateStatus().providerCircuitOpen,true);assert.deepEqual(await module.readCloudState("u1","events",{events:[]}),{events:[]});assert.equal(calls,1);});
test("writes remain locally durable without probing an open provider circuit",async()=>{let calls=0;const {module}=await loadCloudState("circuit-write",async()=>{calls+=1;throw new TypeError("provider unavailable");});await module.readCloudState("u1","tasks",{});assert.equal(await module.writeCloudState("u1","events",{events:["safe"]}),true);assert.equal(calls,1);assert.ok(module.cloudStateStatus().pendingWrites>=1);});
test("checkpoint acceptance does not wait for remote replication",async()=>{let releaseRemote;const remote=new Promise(resolve=>{releaseRemote=resolve;});let calls=0;const {module}=await loadCloudState("checkpoint-fast",async()=>{calls+=1;await remote;return response(true);});const started=Date.now();assert.equal(await module.checkpointCloudState("u1","governed_external_connector",{commands:[{id:"cmd-1"}],events:[],receipts:[]}),true);assert.ok(Date.now()-started<100);assert.deepEqual(await module.readCloudState("u1","governed_external_connector",{}),{commands:[{id:"cmd-1"}],events:[],receipts:[]});assert.equal(calls,1);releaseRemote();await wait(20);});
test("an older replication cannot overwrite a newer dirty checkpoint",async()=>{let releaseFirst;const firstBlocked=new Promise(resolve=>{releaseFirst=resolve;});const bodies=[];const {module}=await loadCloudState("checkpoint-race",async(_url,options)=>{const body=JSON.parse(options.body);bodies.push(body);if(bodies.length===1)await firstBlocked;return response(true);});assert.equal(await module.checkpointCloudState("u1","governed_external_connector",{commands:[{id:"cmd-1"}],events:[],receipts:[]}),true);await wait(10);assert.equal(await module.checkpointCloudState("u1","governed_external_connector",{commands:[{id:"cmd-1"},{id:"cmd-2"}],events:[],receipts:[]}),true);releaseFirst();await wait(30);assert.deepEqual(await module.readCloudState("u1","governed_external_connector",{}),{commands:[{id:"cmd-1"},{id:"cmd-2"}],events:[],receipts:[]});});
test("readiness probe proves a real provider read and caches recent success",async()=>{let calls=0;const {module}=await loadCloudState("health-probe",async(_url,options)=>{calls+=1;assert.equal(JSON.parse(options.body).p_namespace,"health_probe_v1");return response({});});assert.equal(module.cloudStateStatus().lastSuccessAt,null);assert.equal(await module.probeCloudState(),true);assert.ok(module.cloudStateStatus().lastSuccessAt);assert.equal(await module.probeCloudState(),true);assert.equal(calls,1);});
test("readiness probe fails closed when the provider cannot be reached",async()=>{const {module}=await loadCloudState("health-probe-failure",async()=>{throw new TypeError("network unavailable");});assert.equal(await module.probeCloudState(),false);assert.equal(module.cloudStateStatus().healthy,false);assert.equal(module.cloudStateStatus().providerCircuitOpen,true);});
test("concurrent readiness checks share one provider proof",async()=>{let calls=0;const {module}=await loadCloudState("health-probe-singleflight",async()=>{calls+=1;await new Promise(resolve=>setTimeout(resolve,25));return response({});});assert.deepEqual(await Promise.all([module.probeCloudState(),module.probeCloudState(),module.probeCloudState()]),[true,true,true]);assert.equal(calls,1);});
