import test from "node:test";
import assert from "node:assert/strict";
import { createGovernedConnector } from "../src/governed-connector.js";
function harness(options={},shared=null){const box=shared||{state:{schema:"georgie.governed-connector.v1",version:1,commands:[],events:[],receipts:[],updatedAt:null}};const connector=createGovernedConnector({...options,readState:async()=>structuredClone(box.state),writeState:async(_u,next)=>{box.state=structuredClone(next)},retainObjective:async()=>({id:"node"}),transitionObjective:async()=>({id:"node"})});connector.__box=box;return connector;}
async function waitFor(c,u,id,statuses=["completed","blocked","recovering"],timeout=1500){const end=Date.now()+timeout;while(Date.now()<end){const x=await c.status(u,id);if(x&&statuses.includes(x.status))return x;await new Promise(r=>setTimeout(r,5));}throw new Error("wait timeout");}
const input=(key,objective=key)=>({source:"chatgpt",objectiveId:objective,idempotencyKey:key,command:`lease regression ${key}`});
test("long task acknowledges before deep execution completes",async()=>{let release;const gate=new Promise(r=>release=r);const c=harness({executeCommand:async()=>{await gate;return{terminalState:"completed"}}});const t=Date.now(),a=await c.submit("u",input("long"));assert.equal(a.status,"accepted");assert.ok(Date.now()-t<100);assert.equal(a.lease.status,"queued");await new Promise(r=>setTimeout(r,20));assert.equal((await c.status("u",a.commandId)).status,"running");release();await waitFor(c,"u",a.commandId,["completed"]);});
test("provider timeout remains recoverable instead of completed",async()=>{const c=harness({executeCommand:async()=>({completed:false,terminalState:"recovering",exactBlocker:"provider timeout"})});const a=await c.submit("u2",input("timeout"));const x=await waitFor(c,"u2",a.commandId,["recovering"]);assert.equal(x.lease.status,"queued");assert.equal(x.completedAt,undefined);});
test("restart can reclaim stale lease with higher fencing generation",async()=>{const shared={state:{schema:"georgie.governed-connector.v1",version:1,commands:[],events:[],receipts:[],updatedAt:null}};let release;const gate=new Promise(r=>release=r);const a=harness({ownerId:"worker-a",leaseTtlMs:1000,executeCommand:async()=>{await gate;return{terminalState:"completed"}}},shared);const accepted=await a.submit("u3",input("restart"));await new Promise(r=>setTimeout(r,20));shared.state.leases[0].expiresAt=new Date(Date.now()-1).toISOString();let calls=0;const b=harness({ownerId:"worker-b",leaseTtlMs:1000,executeCommand:async()=>{calls++;return{terminalState:"completed"}}},shared);assert.equal((await b.resume("u3")).length,1);const done=await waitFor(b,"u3",accepted.commandId,["completed"]);assert.equal(done.lease.generation,2);assert.equal(calls,1);release();await new Promise(r=>setTimeout(r,20));assert.equal((await b.status("u3",accepted.commandId)).lease.generation,2);});
test("duplicate dispatch reuses same lease and execution",async()=>{let calls=0;const c=harness({executeCommand:async()=>{calls++;await new Promise(r=>setTimeout(r,20));return{terminalState:"completed"}}});const [a,b]=await Promise.all([c.submit("u4",input("dup")),c.submit("u4",input("dup"))]);assert.equal(a.commandId,b.commandId);assert.equal(a.lease.id,b.lease.id);await waitFor(c,"u4",a.commandId,["completed"]);assert.equal(calls,1);});
test("stale worker is fenced after reclaim",async()=>{const shared={state:{schema:"georgie.governed-connector.v1",version:1,commands:[],events:[],receipts:[],updatedAt:null}};let release;const gate=new Promise(r=>release=r);const a=harness({ownerId:"fence-a",leaseTtlMs:1000,executeCommand:async()=>{await gate;return{terminalState:"completed"}}},shared);const accepted=await a.submit("u5",input("fence"));await new Promise(r=>setTimeout(r,20));shared.state.leases[0].expiresAt=new Date(Date.now()-1).toISOString();const b=harness({ownerId:"fence-b",leaseTtlMs:1000,executeCommand:async()=>({terminalState:"completed"})},shared);await b.resume("u5");const done=await waitFor(b,"u5",accepted.commandId,["completed"]);assert.equal(done.lease.generation,2);release();await new Promise(r=>setTimeout(r,30));const final=await b.status("u5",accepted.commandId);assert.equal(final.receipts.filter(r=>r.status==="completed").length,1);assert.equal(final.lease.generation,2);});
test("terminal completion remains exactly once across resume and duplicate",async()=>{let calls=0;const c=harness({executeCommand:async()=>{calls++;return{terminalState:"completed"}}});const a=await c.submit("u6",input("once"));const done=await waitFor(c,"u6",a.commandId,["completed"]);await c.resume("u6");const dup=await c.submit("u6",input("once"));await new Promise(r=>setTimeout(r,20));const final=await c.status("u6",a.commandId);assert.equal(dup.duplicate,true);assert.equal(calls,1);assert.equal(final.receipts.filter(r=>r.status==="completed").length,1);assert.equal(final.lease.terminalReceiptId,done.lease.terminalReceiptId);});
