import test from "node:test";
import assert from "node:assert/strict";
import {ingestRecoveryCandidate,missingStatementMonths,processRecoveryIntent,receiveRecoveryReply,requiredStatementMonths,suppressionDecision} from "../src/financing-recovery.js";
function intake(lane="new"){return {lane,tenantId:"sierra",sourceApplicationId:"cm100-1",email:"Owner@Example.com",firstName:"Ava",jurisdiction:"FL",applicationType:"CM-100",integrityVerified:true,completed:true,consentBasis:{verified:true,evidenceId:"consent-1"},evidenceIds:["app-doc-1"],documents:[]};}
test("new and historical lanes create one canonical deterministic deal and exact request",async()=>{const seen=new Map(),store={async transactIntake(c,i){if(!seen.has(i.key))seen.set(i.key,{c,i});return seen.get(i.key)}};const now=new Date("2026-09-03T00:00:00Z"),a=await ingestRecoveryCandidate(store,intake(),{now}),b=await ingestRecoveryCandidate(store,intake("historical"),{now});assert.equal(seen.size,1);assert.deepEqual(a.c.missingMonths,["2026-08","2026-07","2026-06"]);assert.equal(a.c.rawApplicationCrmWrite,false);assert.equal(a.c.dealId,b.c.dealId)});
test("verified current statements bypass outreach and wake Prism once",async()=>{const input=intake();input.documents=requiredStatementMonths({asOf:new Date("2026-09-03"),jurisdiction:"FL"}).map(statementMonth=>({statementMonth,verified:true}));let calls=0;const result=await ingestRecoveryCandidate({transactIntake:async(c,i)=>{calls++;return i}},input,{now:new Date("2026-09-03")});assert.equal(result.kind,"prism_wakeup");assert.equal(calls,1);assert.deepEqual(missingStatementMonths(requiredStatementMonths({asOf:new Date("2026-09-03"),jurisdiction:"FL"}),input.documents),[])});
test("invalid CM-100 and uncertain consent fail closed",async()=>{await assert.rejects(()=>ingestRecoveryCandidate({}, {...intake(),integrityVerified:false}),/NOT_CANONICAL/);await assert.rejects(()=>ingestRecoveryCandidate({}, {...intake(),consentBasis:{verified:false}}),/CONSENT/)});
test("release hold and global suppression prevent provider calls",async()=>{let sends=0;const base={id:"i",key:"k",kind:"statement_request",missingMonths:["2026-08"],dealId:"d",email:"a@b.com"};const held={checkGlobalSuppression:async()=>({allowed:true}),holdIntent:async(i,r)=>r};assert.equal(await processRecoveryIntent(held,base,{release:"hold",send:async()=>{sends++}}),"RELEASE_HOLD");const blocked={checkGlobalSuppression:async()=>({allowed:false,reason:"opt_out"}),blockIntent:async(i,r)=>r};assert.equal(await processRecoveryIntent(blocked,base,{release:"canary",send:async()=>{sends++}}),"opt_out");assert.equal(sends,0)});
test("retry records exact failure; success requires and persists provider receipt once",async()=>{const intent={id:"i",key:"k",kind:"statement_request",missingMonths:["2026-08"],dealId:"d",email:"a@b.com"};let failure,receipt,sends=0;const store={checkGlobalSuppression:async()=>({allowed:true}),recordProviderFailure:async(i,e)=>failure=e,recordProviderReceipt:async(i,r)=>{receipt=r;return r}};await assert.rejects(()=>processRecoveryIntent(store,intent,{release:"canary",send:async()=>{sends++;throw new Error("SMTP_451")}}),/SMTP_451/);assert.equal(failure,"SMTP_451");await processRecoveryIntent(store,intent,{release:"canary",send:async()=>{sends++;return {messageId:"neo-1",accepted:["a@b.com"]}}});assert.equal(receipt.messageId,"neo-1");assert.equal(sends,2)});
test("reply routing uses exact identity and deterministic idempotency",async()=>{const calls=[];const store={recordReplyAndDocuments:async()=>({complete:true,coverageVersion:"v1",evidenceIds:["doc-1"]}),enqueuePrism:async(i,k)=>calls.push(k)};await receiveRecoveryReply(store,{providerMessageId:"m1",threadId:"t1",dealId:"d1"});await receiveRecoveryReply(store,{providerMessageId:"m1",threadId:"t1",dealId:"d1"});assert.deepEqual(calls,["prism:d1:v1","prism:d1:v1"]);await assert.rejects(()=>receiveRecoveryReply(store,{threadId:"t1",dealId:"d1"}),/EXACT_REPLY/)});
test("suppression and attempt limits are global and fail closed",()=>{assert.equal(suppressionDecision({attempts:0},[{reason:"complaint"}],[]).allowed,false);assert.equal(suppressionDecision({attempts:3},[],[]).reason,"attempt_limit");assert.equal(suppressionDecision({attempts:0},[],[{at:new Date().toISOString()}]).reason,"contact_frequency")});
