import test from "node:test";
import assert from "node:assert/strict";
import { buildIntelligenceControlMap, intelligenceControlMapBrief } from "../src/intelligence-control-map.js";
import { deterministicToolPlan } from "../src/fast-intents.js";

const manifest = { connections: { sierraWorkforce: { state: "configured" }, durableOperationalState: { enabled: true }, deploymentObservability: { github: "configured", vercel: "configured", render: "configured" }, neoMail: { state: "configured" }, smartlead: { state: "configured" }, macAgent: { serverCredentialConfigured: true } }, core: { durableBackgroundOperations: true, governedSelfEvolution: true }, sessionRuntime: { unfinishedWorkRecovery: true, killSwitchActive: false } };
const observations = ["sierra", "github", "vercel", "render", "providers", "operational_state", "background", "revenue", "maintenance", "mac_agent", "mailboxes", "smartlead"].map((id) => ({ id, state: "verified", verifiedAt: "2026-08-21T12:00:00.000Z", evidence: id === "mailboxes" ? [] : {} }));
function map(extra = {}) { return buildIntelligenceControlMap({ manifest, observations, revenue: { active: true, phase: 1 }, background: { active: true, mode: "observe_notify", incidents: [] }, ...extra, generatedAt: "2026-08-21T12:00:00.000Z" }); }

test("map inventories systems and all nine revenue-chain handoffs", () => { const value = map(); assert.equal(value.schema, "georgie.intelligence-control-map.v1"); assert.equal(value.systems.length, 15); assert.equal(value.handoffs.length, 9); assert.deepEqual(value.handoffs.map((item) => item.id), ["intake_to_deal", "deal_to_documents", "documents_to_underwriting", "underwriting_to_capitalmatch", "capitalmatch_to_submission", "submission_to_lender_response", "lender_response_to_closing", "closing_to_funding", "funding_to_crm_accounting"]); assert.ok(value.handoffs.every((item) => item.authoritativeSource && item.invariants.length && item.impact)); });
test("configured access is never represented as live health proof", () => { const value = buildIntelligenceControlMap({ manifest, observations: [], revenue: { active: true } }); assert.equal(value.systems.find((item) => item.id === "sierra_core").configured, true); assert.equal(value.systems.find((item) => item.id === "sierra_core").health, "unknown"); assert.equal(value.certification.endToEndCertified, false); assert.ok(value.gaps.some((item) => item.target === "sierra_core" && item.type === "evidence_gap")); });
test("a successful connector response is separated from explicit health", () => { const value = map(); const capitalMatch = value.systems.find((item) => item.id === "capitalmatch"); assert.equal(capitalMatch.evidenceState, "verified"); assert.equal(capitalMatch.health, "unknown"); assert.equal(value.certification.endToEndCertified, false); });
test("authority, approvals, recovery, escalation and kill switch are explicit", () => { const value = map({ approvals: [{ id: "a1", actionType: "lender_submit", title: "Submit", risk: "high", status: "pending" }] }); assert.equal(value.authority.find((item) => item.capability === "external_message_or_lender_submission").default, "blocked"); assert.equal(value.approvals.pending[0].id, "a1"); assert.equal(value.recovery.globalKillSwitch.available, true); assert.ok(value.notificationRoutes.critical.includes("executive_work_email")); });
test("map contains no credential-shaped fields or secret values", () => { const raw = JSON.stringify(map()); assert.doesNotMatch(raw, /api[_-]?key|service[_-]?role[_-]?key|password|bearer\s|private[_-]?key/i); });
test("brief is executive-readable and does not overclaim", () => { const brief = intelligenceControlMapBrief(buildIntelligenceControlMap({ manifest, observations: [] })); assert.match(brief, /ATTENTION/); assert.match(brief, /Unknown or stale system health/); assert.match(brief, /No credential values/); });
test("control-map language routes to a durable read or live refresh", () => { assert.equal(deterministicToolPlan("Show me the Intelligence and Control Map")[0].tool, "system.intelligence_control_map"); assert.equal(deterministicToolPlan("Refresh the current Intelligence and Control Map")[0].tool, "system.intelligence_control_map_refresh"); });
