import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { reconcileRemoteIdenticalDirtyPaths } from "../mac-agent/git-update-reconcile.js";

const execFileAsync = promisify(execFile);
const run = (file,args,options={}) => execFileAsync(file,args,{...options,maxBuffer:8*1024*1024});
async function git(repo,...args){return run("git",["-C",repo,...args]);}
async function configure(repo){await git(repo,"config","user.email","test@example.com");await git(repo,"config","user.name","Georgie Test");}

test("Phase 2 installer is idempotent against committed runtime sources", async () => {
  const files=["mac-agent/agent.js","src/governed-connector.js","src/tools.js"];
  const before=Object.fromEntries(files.map(file=>[file,fs.readFileSync(file,"utf8")]));
  await run(process.execPath,["scripts/install-seo-phase2-executor.mjs"]);
  const after=Object.fromEntries(files.map(file=>[file,fs.readFileSync(file,"utf8")]));
  assert.deepEqual(after,before);
});

test("remote-identical generated bytes reconcile safely and permit ff-only bootstrap", async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"georgie-remote-identical-"));
  const origin=path.join(root,"origin.git"), seed=path.join(root,"seed"), local=path.join(root,"local"), advance=path.join(root,"advance");
  await run("git",["init","--bare",origin]);
  await run("git",["init","-b","main",seed]); await configure(seed);
  fs.writeFileSync(path.join(seed,"generated.txt"),"v1\n"); await git(seed,"add","generated.txt"); await git(seed,"commit","-m","v1"); await git(seed,"remote","add","origin",origin); await git(seed,"push","-u","origin","main");
  await run("git",["clone","--branch","main",origin,local]); await configure(local);
  await run("git",["clone","--branch","main",origin,advance]); await configure(advance);
  fs.writeFileSync(path.join(advance,"generated.txt"),"v2\n"); await git(advance,"add","generated.txt"); await git(advance,"commit","-m","v2"); await git(advance,"push","origin","main");
  await git(local,"fetch","origin","main");
  fs.writeFileSync(path.join(local,"generated.txt"),"v2\n");
  const result=await reconcileRemoteIdenticalDirtyPaths({repo:local,run});
  assert.equal(result.reconciled,true); assert.deepEqual(result.paths,["generated.txt"]);
  assert.equal((await git(local,"status","--porcelain")).stdout.trim(),"");
  await git(local,"merge","--ff-only","origin/main");
  assert.equal(fs.readFileSync(path.join(local,"generated.txt"),"utf8"),"v2\n");
});

test("unrelated dirty work remains untouched and fails closed", async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"georgie-unrelated-dirty-"));
  await run("git",["init","-b","main",root]); await configure(root);
  fs.writeFileSync(path.join(root,"file.txt"),"base\n"); await git(root,"add","file.txt"); await git(root,"commit","-m","base");
  const bare=path.join(os.tmpdir(),`georgie-origin-${process.pid}-${Date.now()}.git`); await run("git",["clone","--bare",root,bare]); await git(root,"remote","add","origin",bare); await git(root,"fetch","origin","main");
  fs.writeFileSync(path.join(root,"file.txt"),"human work\n");
  const result=await reconcileRemoteIdenticalDirtyPaths({repo:root,run});
  assert.equal(result.reconciled,false);
  assert.equal(fs.readFileSync(path.join(root,"file.txt"),"utf8"),"human work\n");
  assert.notEqual((await git(root,"status","--porcelain")).stdout.trim(),"");
});

test("updater fetches before dirty reconciliation and retains fail-closed guard", () => {
  const source=fs.readFileSync("mac-agent/agent.js","utf8");
  const fetchIndex=source.indexOf('"fetch", "origin", "main"');
  const dirtyIndex=source.indexOf('PRIMARY_MAC_REPO_DIRTY');
  assert.ok(fetchIndex>=0 && dirtyIndex>fetchIndex);
  assert.match(source,/reconcileRemoteIdenticalDirtyPaths/);
  assert.ok(source.includes('runDeveloper("git", ["-C", repo, "merge", "--ff-only", "origin/main"]'));
});
