const VERCEL="https://api.vercel.com";
const RENDER="https://api.render.com/v1";
const clean=(v,max=1000)=>String(v??"").trim().slice(0,max);
function redactEnv(rows=[]){return (Array.isArray(rows)?rows:[]).map(x=>({key:clean(x.key||x.name,160),target:x.target||x.environment||null,type:x.type||null,createdAt:x.createdAt||x.created_at||null,updatedAt:x.updatedAt||x.updated_at||null})).filter(x=>x.key);}
async function json(url,token,{method="GET",body,expected=[200]}={}){if(!token)throw new Error("Deployment provider credential is not configured");const r=await fetch(url,{method,headers:{authorization:`Bearer ${token}`,accept:"application/json",...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null;}catch{data=text;}if(!expected.includes(r.status))throw new Error(`Deployment provider request failed (${r.status}): ${clean(data?.message||data||"",300)}`);return data;}
function requireApproval(input={}){const approvalId=clean(input.approvalId||input._governance?.approvalId,160);if(!approvalId)throw new Error("Explicit approval ID is required for production deployment changes");if(process.env.GEORGIE_AUTOMATION_KILL_SWITCH==="true")throw new Error("Georgie automation kill switch is active");return approvalId;}

export function deploymentControlStatus(){return{vercel:{configured:Boolean(process.env.GEORGIE_VERCEL_TOKEN&&process.env.GEORGIE_VERCEL_TEAM_ID&&process.env.GEORGIE_VERCEL_PROJECT_ID),projectId:process.env.GEORGIE_VERCEL_PROJECT_ID||null,productionPromotion:true,rollback:true,environmentMetadata:true},render:{configured:Boolean(process.env.GEORGIE_RENDER_API_KEY&&process.env.GEORGIE_RENDER_SERVICE_ID),serviceId:process.env.GEORGIE_RENDER_SERVICE_ID||null,currentRedeploy:true,environmentMetadata:true,historicalRollback:"governed_git_revert_then_autodeploy"},productionChangesApprovalRequired:true,rawEnvValuesReturned:false};}

export async function listVercelEnvironmentMetadata(){const token=process.env.GEORGIE_VERCEL_TOKEN,team=process.env.GEORGIE_VERCEL_TEAM_ID,project=process.env.GEORGIE_VERCEL_PROJECT_ID;if(!team||!project)throw new Error("Vercel project is not configured");const d=await json(`${VERCEL}/v9/projects/${encodeURIComponent(project)}/env?teamId=${encodeURIComponent(team)}&decrypt=false`,token);return{provider:"vercel",projectId:project,variables:redactEnv(d?.envs||d||[]),valuesExposed:false};}
export async function promoteVercelDeployment(input={}){const approvalId=requireApproval(input),token=process.env.GEORGIE_VERCEL_TOKEN,team=process.env.GEORGIE_VERCEL_TEAM_ID,project=process.env.GEORGIE_VERCEL_PROJECT_ID,deployment=clean(input.deploymentId,240);if(!project||!team||!deployment)throw new Error("Vercel project/team/deployment are required");await json(`${VERCEL}/v10/projects/${encodeURIComponent(project)}/promote/${encodeURIComponent(deployment)}?teamId=${encodeURIComponent(team)}`,token,{method:"POST",expected:[200,201,202]});return{provider:"vercel",promoted:true,projectId:project,deploymentId:deployment,approvalId};}
export async function rollbackVercelDeployment(input={}){const approvalId=requireApproval(input),token=process.env.GEORGIE_VERCEL_TOKEN,team=process.env.GEORGIE_VERCEL_TEAM_ID,project=process.env.GEORGIE_VERCEL_PROJECT_ID,deployment=clean(input.deploymentId,240);if(!project||!team||!deployment)throw new Error("Vercel project/team/deployment are required");const qs=new URLSearchParams({teamId:team});if(input.description)qs.set("description",clean(input.description,500));await json(`${VERCEL}/v1/projects/${encodeURIComponent(project)}/rollback/${encodeURIComponent(deployment)}?${qs}`,token,{method:"POST",expected:[200,201,202]});return{provider:"vercel",rollbackRequested:true,projectId:project,deploymentId:deployment,approvalId};}

export async function listRenderEnvironmentMetadata(){const token=process.env.GEORGIE_RENDER_API_KEY,service=process.env.GEORGIE_RENDER_SERVICE_ID;if(!service)throw new Error("Render service is not configured");const d=await json(`${RENDER}/services/${encodeURIComponent(service)}/env-vars`,token);const rows=(Array.isArray(d)?d:[]).map(x=>x?.envVar||x).filter(Boolean);return{provider:"render",serviceId:service,variables:redactEnv(rows),valuesExposed:false};}
export async function redeployRender(input={}){const approvalId=requireApproval(input),token=process.env.GEORGIE_RENDER_API_KEY,service=process.env.GEORGIE_RENDER_SERVICE_ID;if(!service)throw new Error("Render service is not configured");const d=await json(`${RENDER}/services/${encodeURIComponent(service)}/deploys`,token,{method:"POST",body:{clearCache:Boolean(input.clearCache)},expected:[200,201,202]});return{provider:"render",redeployRequested:true,serviceId:service,deployId:d?.id||d?.deploy?.id||null,approvalId,clearCache:Boolean(input.clearCache)};}
