import crypto from "crypto";
import { readCloudState, writeCloudState } from "../cloud-state.js";
const NS="mac_jobs"; const PRIMARY=()=>process.env.GEORGIE_PRIMARY_USER_ID||"primary";
async function readStore(userId=PRIMARY()){const s=await readCloudState(userId,NS,{jobs:[]});return{jobs:Array.isArray(s.jobs)?s.jobs:[]};}
async function writeStore(userId,store){await writeCloudState(userId,NS,store);}
export async function enqueueMacJob({userId,deviceId,action,args={},risk="low_risk_write",reason=""}){const uid=String(userId||PRIMARY());const store=await readStore(uid);const job={id:crypto.randomUUID(),userId:uid,deviceId,action,args,risk,reason,status:"queued",createdAt:new Date().toISOString(),claimedAt:null,completedAt:null,result:null,error:null};store.jobs.push(job);store.jobs=store.jobs.slice(-5000);await writeStore(uid,store);return job;}
export async function claimMacJobs(deviceId,limit=5){const uid=PRIMARY();const store=await readStore(uid);const jobs=store.jobs.filter(j=>j.deviceId===deviceId&&j.status==="queued").slice(0,limit);const now=new Date().toISOString();for(const job of jobs){job.status="claimed";job.claimedAt=now;}if(jobs.length)await writeStore(uid,store);return jobs;}
export async function completeMacJob(deviceId,jobId,{result=null,error=null}={}){const uid=PRIMARY();const store=await readStore(uid);const job=store.jobs.find(j=>j.id===jobId&&j.deviceId===deviceId);if(!job)return null;job.status=error?"failed":"completed";job.completedAt=new Date().toISOString();job.result=result;job.error=error;await writeStore(uid,store);return job;}
export async function listMacJobs(userId,limit=50){const uid=String(userId||PRIMARY());const store=await readStore(uid);return store.jobs.filter(j=>j.userId===uid).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,limit);}
