import AppKit
import Foundation
import Carbon.HIToolbox
import Speech
import AVFoundation

enum GeorgieVoiceMode { case idle, wake, command }
final class GeorgieWindowController: NSWindowController, NSTextFieldDelegate, NSSpeechSynthesizerDelegate {
 private let server=URL(string:"https://georgie.onrender.com")!; private let responseView=NSTextView(); private let responseScroll=NSScrollView(); private let input=NSTextField(string:""); private let talkButton=NSButton(); private let copyButton=NSButton(); private let recognizer=SFSpeechRecognizer(locale:Locale(identifier:"en-US")); private let audioEngine=AVAudioEngine(); private var recognitionTask:SFSpeechRecognitionTask?; private var recognitionRequest:SFSpeechAudioBufferRecognitionRequest?; private let speaker=NSSpeechSynthesizer(); private var voiceMode:GeorgieVoiceMode = .idle; private var permissionsReady=false; private var conversationActive=false; private var silenceTimer:Timer?; private var restartTimer:Timer?; private var lastTranscript=""; private var fullResponse=""
 init(){let w=NSPanel(contentRect:NSRect(x:0,y:0,width:500,height:560),styleMask:[.titled,.closable,.utilityWindow,.resizable],backing:.buffered,defer:false);w.title="Georgie";w.isReleasedWhenClosed=false;w.minSize=NSSize(width:440,height:430);w.appearance=NSAppearance(named:.darkAqua);super.init(window:w);speaker.delegate=self;buildUI();requestVoicePermissions()}
 required init?(coder:NSCoder){fatalError()}
 private func setResponse(_ text:String){fullResponse=text;responseView.string=text;responseView.scrollToEndOfDocument(nil);copyButton.isEnabled = !text.isEmpty}
 private func buildUI(){guard let c=window?.contentView else{return};let title=NSTextField(labelWithString:"GEORGIE");title.font=.systemFont(ofSize:28,weight:.semibold);title.alignment=.center;title.frame=NSRect(x:30,y:480,width:440,height:40);c.addSubview(title);responseScroll.frame=NSRect(x:34,y:205,width:432,height:255);responseScroll.hasVerticalScroller=true;responseScroll.autohidesScrollers=true;responseScroll.borderType=.noBorder;responseView.isEditable=false;responseView.isSelectable=true;responseView.drawsBackground=false;responseView.font=.systemFont(ofSize:15);responseView.textColor=.labelColor;responseView.textContainerInset=NSSize(width:6,height:6);responseView.isVerticallyResizable=true;responseView.isHorizontallyResizable=false;responseView.autoresizingMask=[.width];responseView.textContainer?.widthTracksTextView=true;responseScroll.documentView=responseView;c.addSubview(responseScroll);copyButton.title="Copy Full Response";copyButton.target=self;copyButton.action=#selector(copyFullResponse);copyButton.frame=NSRect(x:316,y:170,width:150,height:28);copyButton.isEnabled=false;c.addSubview(copyButton);talkButton.title="🎙 TALK TO GEORGIE";talkButton.target=self;talkButton.action=#selector(toggleVoice);talkButton.frame=NSRect(x:34,y:118,width:432,height:42);c.addSubview(talkButton);input.frame=NSRect(x:34,y:66,width:330,height:38);input.placeholderString="Ask Georgie…";input.delegate=self;c.addSubview(input);let send=NSButton(title:"Send",target:self,action:#selector(sendPressed));send.frame=NSRect(x:372,y:66,width:94,height:38);c.addSubview(send);let hint=NSTextField(labelWithString:"Say ‘Hey Georgie’ or press ⌥ Space");hint.frame=NSRect(x:34,y:25,width:432,height:22);hint.alignment=.center;c.addSubview(hint)}
 @objc private func copyFullResponse(){guard !fullResponse.isEmpty else{return};NSPasteboard.general.clearContents();NSPasteboard.general.setString(fullResponse,forType:.string)}
 private func requestVoicePermissions(){SFSpeechRecognizer.requestAuthorization{[weak self] s in AVCaptureDevice.requestAccess(for:.audio){g in DispatchQueue.main.async{guard let self else{return};self.permissionsReady=s == .authorized && g;if self.permissionsReady{self.setResponse("Ready. Say ‘Hey Georgie’.");self.startWakeListening()}else{self.setResponse("Enable Microphone and Speech Recognition.")}}}}}
 func show(){NSApp.activate(ignoringOtherApps:true);window?.center();showWindow(nil);input.becomeFirstResponder()}
 func beginConversation(){show();conversationActive=true;startCommandListening()}
 func control(_ control:NSControl,textView:NSTextView,doCommandBy selector:Selector)->Bool{if selector == #selector(NSResponder.insertNewline(_:)){sendPressed();return true};return false}
 @objc private func toggleVoice(){if voiceMode == .command && audioEngine.isRunning{finishCommand()}else{beginConversation()}}
 private func stopCapture(){silenceTimer?.invalidate();silenceTimer=nil;restartTimer?.invalidate();restartTimer=nil;if audioEngine.isRunning{audioEngine.stop();audioEngine.inputNode.removeTap(onBus:0)};recognitionRequest?.endAudio();recognitionTask?.cancel();recognitionRequest=nil;recognitionTask=nil;voiceMode = .idle}
 private func makeRecognitionRequest()->SFSpeechAudioBufferRecognitionRequest{let r=SFSpeechAudioBufferRecognitionRequest();r.shouldReportPartialResults=true;if #available(macOS 13.0,*){r.requiresOnDeviceRecognition=recognizer?.supportsOnDeviceRecognition ?? false};return r}
 private func startAudio(_ r:SFSpeechAudioBufferRecognitionRequest)->Bool{let n=audioEngine.inputNode;let f=n.outputFormat(forBus:0);n.removeTap(onBus:0);n.installTap(onBus:0,bufferSize:1024,format:f){[weak self] b,_ in self?.recognitionRequest?.append(b)};audioEngine.prepare();do{try audioEngine.start();return true}catch{setResponse("Microphone error: \(error.localizedDescription)");return false}}
 private func extractWakeRemainder(_ text:String)->String?{let lower=text.lowercased();for p in ["hey georgie","hey georgy","hey george"]{if let r=lower.range(of:p){return String(text[r.upperBound...]).trimmingCharacters(in:CharacterSet(charactersIn:" ,.!?"))}};return nil}
 private func startWakeListening(){guard permissionsReady,!speaker.isSpeaking else{return};stopCapture();conversationActive=false;lastTranscript="";let r=makeRecognitionRequest();recognitionRequest=r;voiceMode = .wake;guard startAudio(r) else{return};talkButton.title="● HEY GEORGIE READY";recognitionTask=recognizer?.recognitionTask(with:r){[weak self] result,error in guard let self else{return};if let result,let remainder=self.extractWakeRemainder(result.bestTranscription.formattedString){DispatchQueue.main.async{guard self.voiceMode == .wake else{return};self.stopCapture();self.conversationActive=true;self.show();if remainder.isEmpty{self.startCommandListening()}else{self.handle(remainder)}};return};if error != nil || result?.isFinal == true{DispatchQueue.main.async{self.restartWakeSoon()}}}}
 private func restartWakeSoon(){guard !conversationActive else{return};stopCapture();restartTimer=Timer.scheduledTimer(withTimeInterval:0.7,repeats:false){[weak self] _ in self?.startWakeListening()}}
 private func startCommandListening(){guard permissionsReady,!speaker.isSpeaking else{return};stopCapture();conversationActive=true;lastTranscript="";let r=makeRecognitionRequest();recognitionRequest=r;voiceMode = .command;guard startAudio(r) else{return};talkButton.title="■ LISTENING…";setResponse("Listening…");recognitionTask=recognizer?.recognitionTask(with:r){[weak self] result,error in guard let self else{return};if let result{let t=result.bestTranscription.formattedString;DispatchQueue.main.async{guard self.voiceMode == .command else{return};self.lastTranscript=t;self.input.stringValue=t;self.silenceTimer?.invalidate();if !t.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty{self.silenceTimer=Timer.scheduledTimer(withTimeInterval:2.8,repeats:false){[weak self] _ in self?.finishCommand()}};if result.isFinal{self.finishCommand()}}}else if error != nil{DispatchQueue.main.async{if self.voiceMode == .command{if self.lastTranscript.isEmpty{self.endConversation()}else{self.finishCommand()}}}}}}
 private func finishCommand(){guard voiceMode == .command else{return};let spoken=lastTranscript.trimmingCharacters(in:.whitespacesAndNewlines);stopCapture();talkButton.title="🎙 TALK TO GEORGIE";if spoken.isEmpty{endConversation()}else{handle(spoken)}}
 private func endConversation(){conversationActive=false;stopCapture();setResponse("Ready. Say ‘Hey Georgie’.");startWakeListening()}
 @objc private func sendPressed(){let t=input.stringValue.trimmingCharacters(in:.whitespacesAndNewlines);guard !t.isEmpty else{return};conversationActive=true;stopCapture();handle(t)}
 private func handle(_ text:String){input.stringValue="";let q=text.lowercased().trimmingCharacters(in:.whitespacesAndNewlines);if ["stop","quiet","enough","hold on","georgie stop","stop talking"].contains(q){speaker.stopSpeaking();setResponse("Stopped.");startCommandListening();return};setResponse("Working…");askCloud(text)}
 private func say(_ text:String){stopCapture();speaker.stopSpeaking();speaker.startSpeaking(text)}
 func speechSynthesizer(_ sender:NSSpeechSynthesizer,didFinishSpeaking finished:Bool){DispatchQueue.main.asyncAfter(deadline:.now()+0.2){if self.conversationActive{self.startCommandListening()}else{self.startWakeListening()}}}
 private func askCloud(_ text:String){var r=URLRequest(url:server.appendingPathComponent("api/respond"));r.httpMethod="POST";r.timeoutInterval=30;r.setValue("application/json",forHTTPHeaderField:"Content-Type");r.setValue("primary",forHTTPHeaderField:"X-Georgie-User");r.setValue("native-mac",forHTTPHeaderField:"X-Georgie-Session");r.httpBody=try? JSONSerialization.data(withJSONObject:["input":text,"history":[]]);URLSession.shared.dataTask(with:r){[weak self] data,_,error in DispatchQueue.main.async{guard let self else{return};if let error{self.setResponse("Cloud error: \(error.localizedDescription)");self.endConversation();return};guard let data,let o=try? JSONSerialization.jsonObject(with:data) as? [String:Any] else{self.endConversation();return};let reply=(o["text"] as? String) ?? (o["error"] as? String) ?? "No response.";self.setResponse(reply);self.say(reply)}}.resume()}
}
final class AppDelegate:NSObject,NSApplicationDelegate{let windowController=GeorgieWindowController();var statusItem:NSStatusItem!;var hotKeyRef:EventHotKeyRef?;func applicationDidFinishLaunching(_ n:Notification){statusItem=NSStatusBar.system.statusItem(withLength:NSStatusItem.squareLength);statusItem.button?.image=NSImage(systemSymbolName:"waveform.circle.fill",accessibilityDescription:"Georgie");let menu=NSMenu();menu.addItem(NSMenuItem(title:"Open Georgie",action:#selector(showGeorgie),keyEquivalent:""));menu.addItem(NSMenuItem.separator());menu.addItem(NSMenuItem(title:"Quit Georgie",action:#selector(NSApplication.terminate(_:)),keyEquivalent:"q"));statusItem.menu=menu;registerHotKey()};private func registerHotKey(){var id=EventHotKeyID(signature:OSType(0x47454F52),id:1);RegisterEventHotKey(UInt32(kVK_Space),UInt32(optionKey),id,GetApplicationEventTarget(),0,&hotKeyRef);InstallEventHandler(GetApplicationEventTarget(),{_,_,u in guard let u else{return noErr};Unmanaged<AppDelegate>.fromOpaque(u).takeUnretainedValue().showGeorgie();return noErr},1,[EventTypeSpec(eventClass:OSType(kEventClassKeyboard),eventKind:UInt32(kEventHotKeyPressed))],Unmanaged.passUnretained(self).toOpaque(),nil)};@objc func showGeorgie(){windowController.beginConversation()}}
let app=NSApplication.shared;let delegate=AppDelegate();app.delegate=delegate;app.setActivationPolicy(.accessory);app.run()