import AVFoundation
import Foundation

final class GeorgieRealtimeVoice: NSObject {
    private let endpoint = URL(string: "wss://georgie.onrender.com/api/realtime?userId=primary")!
    private let session = URLSession(configuration: .default)
    private var socket: URLSessionWebSocketTask?
    private let captureEngine = AVAudioEngine()
    private let playbackEngine = AVAudioEngine()
    private let player = AVAudioPlayerNode()
    private var converter: AVAudioConverter?
    private var running = false
    private var playbackReady = false
    var onReady:(()->Void)?; var onUserTranscript:((String)->Void)?; var onAssistantTranscript:((String)->Void)?; var onError:((String)->Void)?; var onSpeakingChanged:((Bool)->Void)?
    override init(){super.init();playbackEngine.attach(player);let f=AVAudioFormat(commonFormat:.pcmFormatFloat32,sampleRate:24000,channels:1,interleaved:false)!;playbackEngine.connect(player,to:playbackEngine.mainMixerNode,format:f);playbackEngine.prepare();do{try playbackEngine.start();playbackReady=true}catch{playbackReady=false}}
    var isActive:Bool{running}; var isSpeaking:Bool{player.isPlaying}
    @discardableResult func start()->Bool{if running{return true};running=true;var request=URLRequest(url:endpoint);request.timeoutInterval=20;request.setValue("primary",forHTTPHeaderField:"X-Georgie-User");let task=session.webSocketTask(with:request);socket=task;task.resume();receiveNext();return true}
    func stop(){running=false;stopCapture();stopPlayback();socket?.cancel(with:.goingAway,reason:nil);socket=nil}
    func stopSpeaking(){stopPlayback();sendJSON(["type":"response.cancel"]);onSpeakingChanged?(false)}
    func sendText(_ text:String){let q=text.trimmingCharacters(in:.whitespacesAndNewlines).lowercased();if ["stop","quiet","enough","hold on","georgie stop","stop talking"].contains(q){stopSpeaking();return};sendJSON(["type":"text","text":text])}
    private func receiveNext(){guard running,let socket else{return};socket.receive{[weak self] result in guard let self,self.running else{return};switch result{case .failure(let e):DispatchQueue.main.async{self.onError?(e.localizedDescription)};self.stop();case .success(let m):let t:String;switch m{case .string(let v):t=v;case .data(let d):t=String(data:d,encoding:.utf8) ?? "";@unknown default:t=""};self.handleServerMessage(t);self.receiveNext()}}}
    private func handleServerMessage(_ text:String){guard let d=text.data(using:.utf8),let o=try? JSONSerialization.jsonObject(with:d) as? [String:Any],let type=o["type"] as? String else{return};switch type{case "georgie.realtime.ready","session.updated":if !captureEngine.isRunning{startCapture()};DispatchQueue.main.async{self.onReady?()};case "input_audio_buffer.speech_started":stopPlayback();sendJSON(["type":"response.cancel"]);DispatchQueue.main.async{self.onSpeakingChanged?(false)};case "response.output_audio.delta":if let x=o["delta"] as? String,let a=Data(base64Encoded:x){playPCM16(a)};case "response.output_audio_transcript.delta":if let x=o["delta"] as? String,!x.isEmpty{DispatchQueue.main.async{self.onAssistantTranscript?(x)}};case "conversation.item.input_audio_transcription.completed","conversation.item.input_audio_transcription.done":if let x=o["transcript"] as? String,!x.isEmpty{let q=x.trimmingCharacters(in:.whitespacesAndNewlines).lowercased();if ["stop","quiet","enough","hold on","georgie stop","stop talking"].contains(q){self.stopSpeaking()};DispatchQueue.main.async{self.onUserTranscript?(x)}};case "response.output_audio.done","response.done":DispatchQueue.main.async{self.onSpeakingChanged?(false)};case "error","georgie.error":let m:String;if let e=o["error"] as? [String:Any]{m=e["message"] as? String ?? "Realtime error"}else{m=o["error"] as? String ?? "Realtime error"};DispatchQueue.main.async{self.onError?(m)};default:break}}
    private func startCapture(){guard running,!captureEngine.isRunning else{return};let input=captureEngine.inputNode;let sf=input.outputFormat(forBus:0);guard sf.sampleRate>0 else{onError?("Microphone format unavailable");return};guard let tf=AVAudioFormat(commonFormat:.pcmFormatInt16,sampleRate:24000,channels:1,interleaved:false),let c=AVAudioConverter(from:sf,to:tf) else{onError?("Could not prepare realtime audio conversion");return};converter=c;input.removeTap(onBus:0);input.installTap(onBus:0,bufferSize:960,format:sf){[weak self] b,_ in self?.convertAndSend(b,converter:c,targetFormat:tf)};captureEngine.prepare();do{try captureEngine.start()}catch{onError?("Microphone start failed: \(error.localizedDescription)")}}
    private func stopCapture(){if captureEngine.isRunning{captureEngine.stop()};captureEngine.inputNode.removeTap(onBus:0);converter=nil}
    private func convertAndSend(_ input:AVAudioPCMBuffer,converter:AVAudioConverter,targetFormat:AVAudioFormat){let ratio=targetFormat.sampleRate/input.format.sampleRate;let cap=AVAudioFrameCount(max(1,Int(Double(input.frameLength)*ratio)+64));guard let out=AVAudioPCMBuffer(pcmFormat:targetFormat,frameCapacity:cap) else{return};var supplied=false;var err:NSError?;let status=converter.convert(to:out,error:&err){_,s in if supplied{s.pointee = .noDataNow;return nil};supplied=true;s.pointee = .haveData;return input};guard status != .error,err == nil,out.frameLength>0,let ch=out.int16ChannelData?[0] else{return};let bytes=Data(bytes:ch,count:Int(out.frameLength)*MemoryLayout<Int16>.size);sendJSON(["type":"audio","audio":bytes.base64EncodedString()])}
    private func sendJSON(_ obj:[String:Any]){guard running,let socket,let d=try? JSONSerialization.data(withJSONObject:obj),let s=String(data:d,encoding:.utf8) else{return};socket.send(.string(s)){[weak self] e in if let e{DispatchQueue.main.async{self?.onError?(e.localizedDescription)}}}}
    private func playPCM16(_ data:Data){guard playbackReady,!data.isEmpty else{return};let n=data.count/MemoryLayout<Int16>.size;guard n>0,let f=AVAudioFormat(commonFormat:.pcmFormatFloat32,sampleRate:24000,channels:1,interleaved:false),let b=AVAudioPCMBuffer(pcmFormat:f,frameCapacity:AVAudioFrameCount(n)),let floats=b.floatChannelData?[0] else{return};b.frameLength=AVAudioFrameCount(n);data.withUnsafeBytes{raw in let s=raw.bindMemory(to:Int16.self);for i in 0..<n{floats[i]=Float(s[i])/32768.0}};if !player.isPlaying{player.play();DispatchQueue.main.async{self.onSpeakingChanged?(true)}};player.scheduleBuffer(b,completionHandler:nil)}
    private func stopPlayback(){if player.isPlaying{player.stop()}}
}
