import crypto from "crypto";
import fs from "fs/promises";
import os from "os";
import path from "path";

const CLOUD_URL = String(process.env.GEORGIE_SUPABASE_URL || "").replace(/\/$/, "");
const CLOUD_KEY = String(process.env.GEORGIE_SUPABASE_SERVICE_ROLE_KEY || "");
const ENABLED = Boolean(CLOUD_URL && CLOUD_KEY);
const REQUEST_TIMEOUT_MS = boundedNumber(process.env.GEORGIE_CLOUD_STATE_TIMEOUT_MS, 12_000, 250, 60_000);
const MAX_ATTEMPTS = boundedNumber(process.env.GEORGIE_CLOUD_STATE_MAX_ATTEMPTS, 3, 1, 5);
const MAX_CONCURRENCY = boundedNumber(process.env.GEORGIE_CLOUD_STATE_CONCURRENCY, 3, 1, 12);
const RETRY_BASE_MS = boundedNumber(process.env.GEORGIE_CLOUD_STATE_RETRY_BASE_MS, 200, 0, 5_000);
const DATA_ROOT = path.resolve(process.env.GEORGIE_DATA_DIR || path.join(os.tmpdir(), "georgie-data"), "cloud-state");
let lastError = null, lastSuccessAt = null, activeRequests = 0, storageMode = "unresolved", pendingWrites = 0;
const waiters = [], readsInFlight = new Map(), writesInFlight = new Map();

function boundedNumber(value, fallback, min, max) { const parsed=Number(value); return Number.isFinite(parsed)?Math.min(max,Math.max(min,Math.trunc(parsed))):fallback; }
function headers(){return {"content-type":"application/json",apikey:CLOUD_KEY,authorization:`Bearer ${CLOUD_KEY}`};}
function stateKey(userId,namespace){return `${String(userId||"primary")}\u0000${String(namespace)}`;}
function fileKey(userId,namespace){return crypto.createHash("sha256").update(stateKey(userId,namespace)).digest("hex");}
function clone(value){return value==null?value:structuredClone(value);}
function errorMessage(error){return error instanceof Error?error.message:String(error);}
function retryable(error){return error?.name==="AbortError"||error?.name==="TimeoutError"||!Number.isFinite(error?.status)||error.status===408||error.status===429||error.status>=500;}
function delay(ms){return ms>0?new Promise(resolve=>setTimeout(resolve,ms)):Promise.resolve();}
async function acquire(){if(activeRequests<MAX_CONCURRENCY){activeRequests+=1;return;}await new Promise(resolve=>waiters.push(resolve));activeRequests+=1;}
function release(){activeRequests=Math.max(0,activeRequests-1);waiters.shift()?.();}
async function oneRpc(name,body){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);timer.unref?.();try{const response=await fetch(`${CLOUD_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(),body:JSON.stringify(body),signal:controller.signal});if(!response.ok){const error=new Error(`${name} failed (${response.status})`);error.status=response.status;throw error;}return await response.json();}catch(error){if(controller.signal.aborted){const timeout=new Error(`cloud state request timed out after ${REQUEST_TIMEOUT_MS}ms`);timeout.name="TimeoutError";throw timeout;}throw error;}finally{clearTimeout(timer);}}
async function rpc(name,body){await acquire();try{let finalError;for(let attempt=1;attempt<=MAX_ATTEMPTS;attempt+=1){try{return await oneRpc(name,body);}catch(error){finalError=error;if(attempt===MAX_ATTEMPTS||!retryable(error))break;await delay(RETRY_BASE_MS*(2**(attempt-1))+Math.floor(Math.random()*50));}}throw finalError;}finally{release();}}
async function ensureLocalDir(){try{await fs.mkdir(DATA_ROOT,{recursive:true,mode:0o700});storageMode=DATA_ROOT.startsWith(os.tmpdir())?"runtime_temp":"local_disk";return true;}catch(error){storageMode="unavailable";console.warn("Cloud state recovery storage unavailable:",errorMessage(error));return false;}}
async function readMirror(userId,namespace){if(!await ensureLocalDir())return null;try{return JSON.parse(await fs.readFile(path.join(DATA_ROOT,`${fileKey(userId,namespace)}.json`),"utf8"));}catch(error){if(error?.code!=="ENOENT")console.warn(`Cloud state recovery read failed for ${namespace}:`,errorMessage(error));return null;}}
async function writeMirror(userId,namespace,state,dirty){if(!await ensureLocalDir())return false;const target=path.join(DATA_ROOT,`${fileKey(userId,namespace)}.json`),temp=`${target}.${process.pid}.${Date.now()}.tmp`;const record={version:1,userId:String(userId||"primary"),namespace:String(namespace),state,dirty:Boolean(dirty),updatedAt:new Date().toISOString()};try{await fs.writeFile(temp,JSON.stringify(record),{mode:0o600});await fs.rename(temp,target);return true;}catch(error){await fs.unlink(temp).catch(()=>{});console.warn(`Cloud state recovery write failed for ${namespace}:`,errorMessage(error));return false;}}
async function putCloud(userId,namespace,state){await rpc("georgie_put_operational_state",{p_user_id:String(userId||"primary"),p_namespace:String(namespace),p_state:state});lastError=null;lastSuccessAt=new Date().toISOString();const mirror=await readMirror(userId,namespace);if(mirror?.dirty)pendingWrites=Math.max(0,pendingWrites-1);await writeMirror(userId,namespace,state,false);}

export function cloudStateStatus(){return {enabled:ENABLED,healthy:ENABLED?!lastError:true,degraded:Boolean(ENABLED&&lastError),lastError,lastSuccessAt,timeoutMs:REQUEST_TIMEOUT_MS,maxAttempts:MAX_ATTEMPTS,maxConcurrency:MAX_CONCURRENCY,recoveryStorage:storageMode,pendingWrites};}
export async function readCloudState(userId,namespace,fallback={}){if(!ENABLED)return clone(fallback);const key=stateKey(userId,namespace);if(readsInFlight.has(key))return clone(await readsInFlight.get(key));const work=(async()=>{const prior=await readMirror(userId,namespace);if(prior?.dirty){try{await putCloud(userId,namespace,prior.state);return prior.state;}catch(error){lastError=errorMessage(error);console.warn(`Cloud state recovery remains deferred for ${namespace}:`,lastError);return prior.state;}}try{const value=await rpc("georgie_get_operational_state",{p_user_id:String(userId||"primary"),p_namespace:String(namespace)});lastError=null;lastSuccessAt=new Date().toISOString();const normalized=value&&typeof value==="object"&&!Array.isArray(value)?value:clone(fallback);await writeMirror(userId,namespace,normalized,false);return normalized;}catch(error){lastError=errorMessage(error);console.warn(`Cloud state read failed for ${namespace}:`,lastError);if(prior?.state&&typeof prior.state==="object"&&!Array.isArray(prior.state))return prior.state;return clone(fallback);}})();readsInFlight.set(key,work);try{return clone(await work);}finally{readsInFlight.delete(key);}}
async function performWrite(userId,namespace,state){const existing=await readMirror(userId,namespace);const locallyDurable=await writeMirror(userId,namespace,state,true);if(locallyDurable&&!existing?.dirty)pendingWrites+=1;try{await putCloud(userId,namespace,state);return true;}catch(error){lastError=errorMessage(error);console.warn(`Cloud state write deferred for ${namespace}:`,lastError);return locallyDurable;}}
export async function writeCloudState(userId,namespace,state){if(!ENABLED)return false;const key=stateKey(userId,namespace),prior=writesInFlight.get(key)||Promise.resolve();const work=prior.catch(()=>{}).then(()=>performWrite(userId,namespace,state));writesInFlight.set(key,work);try{return await work;}finally{if(writesInFlight.get(key)===work)writesInFlight.delete(key);}}
export async function recoverCloudStateWrites({limit=25}={}){if(!ENABLED||!await ensureLocalDir())return {attempted:0,recovered:0,remaining:pendingWrites};let attempted=0,recovered=0;const files=(await fs.readdir(DATA_ROOT).catch(()=>[])).filter(name=>name.endsWith(".json"));const records=await Promise.all(files.map(file=>fs.readFile(path.join(DATA_ROOT,file),"utf8").then(JSON.parse).catch(()=>null)));const dirty=records.filter(record=>record?.dirty);for(const record of dirty.slice(0,Math.max(1,Number(limit)||25))){attempted+=1;try{await putCloud(record.userId,record.namespace,record.state);recovered+=1;}catch(error){lastError=errorMessage(error);}}const remainingRecords=await Promise.all(files.map(file=>fs.readFile(path.join(DATA_ROOT,file),"utf8").then(JSON.parse).catch(()=>null)));pendingWrites=remainingRecords.filter(record=>record?.dirty).length;return {attempted,recovered,remaining:pendingWrites};}
export function startCloudStateRecovery(){if(!ENABLED)return null;const intervalMs=boundedNumber(process.env.GEORGIE_CLOUD_STATE_RECOVERY_INTERVAL_MS,30_000,5_000,600_000);recoverCloudStateWrites().catch(error=>{lastError=errorMessage(error);});const timer=setInterval(()=>recoverCloudStateWrites().catch(error=>{lastError=errorMessage(error);}),intervalMs);timer.unref?.();return timer;}
