import "dotenv/config";
import express from "express";
import multer from "multer";
import helmet from "helmet";
import { rateLimit } from "express-rate-limit";
import path from "path";
import { fileURLToPath } from "url";
import { askGeorgie, extractMemoryCandidates, planActions, spokenResponseFor, synthesizeSpeech, transcribeAudio } from "./georgie.js";
import { addMemory, appendSessionTurn, buildMemoryContext, deleteMemory, getMemoryStorageStatus, getProfile, getSessionHistory, listMemories, searchMemories, updateProfile } from "./memory.js";
import { createTask, deleteTask, listTasks, updateTask } from "./tasks.js";
import { acknowledgeEvent, listEvents } from "./events.js";
import { startProactiveEngine } from "./proactive.js";
import { startEmailIntelligence, sweepNeoMail } from "./email-worker.js";
import { listNeoMailboxes, neoMailConfigured, verifyNeoMailbox } from "./integrations/neo-mail.js";
import { sierraWorkforceConfigured } from "./integrations/sierra-workforce.js";
import { createMacRouter, getMacDeviceStatus } from "./mac/router.js";
import { enqueueMacJob, listMacJobs, macQueueStorageStatus } from "./mac/queue.js";
import { executeTool, listToolDefinitions, startApprovalDispatchWorker } from "./tools.js";
import { cloudStateStatus, startCloudStateRecovery } from "./cloud-state.js";
import { createMobileRouter, startMobileTurnRecovery } from "./mobile-router.js";
import { createSierraRouter } from "./sierra-router.js";
import { createCommandRouter } from "./command-router.js";
import { completeTurnV2 } from "./v2-turn-engine.js";
import { attachRealtimeRelay } from "./realtime-relay.js";
import { startMaintenanceSentinel } from "./maintenance-sentinel.js";
import { startReconciliationWorkers } from "./reconciliation-workers.js";
import { authenticateNativeRequest } from "./mobile-auth.js";
import { requestOwnerRecovery } from "./owner-recovery.js";
import { startWorldStateSentinel } from "./world-state-sentinel.js";
import { startRevenueController } from "./revenue-controller.js";
import { startSelfEvolution } from "./self-evolution.js";
import { startBackgroundOperatingLayer } from "./background-operating-layer.js";
import { intelligenceControlMapStatus, refreshIntelligenceControlMap, startIntelligenceControlMap } from "./intelligence-control-map.js";
import { startEngineeringCoordinator } from "./engineering-coordinator.js";
import { createGovernedConnectorRouter } from "./governed-connector.js";
import { createPortableMcpRouter } from "./portable-connector-mcp.js";
import { createConnectorOAuthRouter } from "./connector-oauth.js";

const app=express();const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024}});const __dirname=path.dirname(fileURLToPath(import.meta.url));const publicDir=path.resolve(__dirname,"../public");
app.disable("x-powered-by");app.set("trust proxy",1);app.use(createConnectorOAuthRouter());app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'"],imgSrc:["'self'","data:","blob:"],mediaSrc:["'self'","blob:","data:"],connectSrc:["'self'"],workerSrc:["'self'","blob:"]}}}));app.use(express.json({limit:"10mb"}));app.use("/api",rateLimit({windowMs:60000,limit:Number(process.env.GEORGIE_RATE_LIMIT||90),standardHeaders:"draft-7",legacyHeaders:false}));app.post("/api/mobile/recovery/request",async(req,res)=>{try{const result=await requestOwnerRecovery({clientKey:req.ip||"unknown"});res.set("Cache-Control","no-store").status(202).json({ok:true,...result});}catch(error){const status=error?.code==="rate_limited"?429:503;res.set("Cache-Control","no-store").status(status).json({ok:false,error:error instanceof Error?error.message:"Recovery request failed"});}});app.use("/api/mobile",createMobileRouter());app.use(express.static(publicDir,{maxAge:process.env.NODE_ENV==="production"?"5m":0}));app.get("/",(_req,res)=>res.set("Cache-Control","no-cache").sendFile(path.join(publicDir,"index.html")));
const protectedLegacyPaths=["/api/profile","/api/memories","/api/tasks","/api/events","/api/session","/api/transcribe","/api/respond","/api/speak","/api/voice-turn","/api/mail","/api/sierra","/api/intelligence-control-map"];
app.use(protectedLegacyPaths,async(req,res,next)=>{try{const device=await authenticateNativeRequest(req);if(!device)return res.status(401).json({ok:false,error:"Secure enrolled-device authentication required"});req.georgieDevice=device;next();}catch{return res.status(503).json({ok:false,error:"Secure device authentication unavailable"});}});
app.use("/api/command-center",createCommandRouter());
function getUserId(req){if(req.georgieDevice)return String(process.env.GEORGIE_PRIMARY_USER_ID||"primary").slice(0,100);return String(req.headers["x-georgie-user"]||req.body?.userId||req.query?.userId||process.env.GEORGIE_PRIMARY_USER_ID||"primary").slice(0,100)}function getSessionId(req){return String(req.headers["x-georgie-session"]||req.body?.sessionId||req.query?.sessionId||"default").slice(0,150)}
app.use("/api/sierra",(req,_res,next)=>{req.georgieUserId=getUserId(req);next();},createSierraRouter());
function readinessSnapshot(){const openAI=Boolean(process.env.OPENAI_API_KEY),neoMail=neoMailConfigured(),sierraWorkforce=sierraWorkforceConfigured(),macAgent=Boolean(process.env.GEORGIE_MAC_AGENT_TOKEN),memoryStorage=getMemoryStorageStatus(),operationalStorage=cloudStateStatus(),macQueue=macQueueStorageStatus(),blockers=[];if(!openAI)blockers.push("OPENAI_API_KEY");if(!memoryStorage.durable)blockers.push("durable_memory_not_connected");if(!operationalStorage.enabled)blockers.push("durable_operational_state_not_connected");return{ready:blockers.length===0,activationState:blockers.length?"connection_pending":"core_ready",blockers,optionalConnections:{neoMail,macAgent,sierraWorkforce},connections:{openAI,neoMail,sierraWorkforce,macAgent,liveWebResearch:process.env.GEORGIE_WEB_ENABLED!=="false",memoryStorage,operationalStorage,macQueue},platform:{voice:true,wakeName:true,memory:true,tasks:true,proactiveEngine:true,emailIntelligence:true,toolRouter:true,sierraWorkforce:true,macRemoteAgent:true,pwa:true,productionSecurity:true,durableOperationalState:true,nativeIOS:true,nativeDeviceAuth:true}}}
async function rememberTurn(userId,userText,assistantText){try{const candidates=await extractMemoryCandidates(userText,assistantText);await Promise.all(candidates.map(memory=>addMemory({userId,...memory,source:"auto-extracted"})));return candidates.length}catch(error){console.warn("Memory extraction skipped:",error instanceof Error?error.message:error);return 0}}
async function runPlannedActions(userId,input){const actions=await planActions(input,listToolDefinitions());const policy=process.env.GEORGIE_AUTO_ACTION_POLICY||"low_risk_write";const results=[];for(const action of actions)results.push(await executeTool({name:action.tool,args:action.args||{},userId,policy}));return results}
const FAST_APPS=new Map([["safari","Safari"],["chrome","Google Chrome"],["google chrome","Google Chrome"],["notes","Notes"],["mail","Mail"],["finder","Finder"],["calendar","Calendar"],["messages","Messages"],["preview","Preview"],["system settings","System Settings"],["excel","Microsoft Excel"],["word","Microsoft Word"],["adobe acrobat reader","Adobe Acrobat Reader"]]);
function parseFastMacCommand(input){const text=String(input||"").trim().toLowerCase().replace(/^georgie[,:]?\s*/,"");const m=text.match(/^(?:please\s+)?(?:open|launch|start)\s+(.+?)(?:\s+(?:please|for me))?$/);if(!m)return null;const app=FAST_APPS.get(m[1].trim());return app?{action:"app.open",app}:null;}
async function waitForMacJob(userId,jobId,timeoutMs=9000){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){const jobs=await listMacJobs(userId,80);const job=jobs.find(j=>j.id===jobId);if(job&&["completed","failed"].includes(job.status))return job;await new Promise(r=>setTimeout(r,250));}return null;}
async function tryFastMacTurn(userId,input){const command=parseFastMacCommand(input);if(!command)return null;const job=await enqueueMacJob({userId,deviceId:"primary-mac",action:command.action,args:{app:command.app},risk:"low_risk_write",reason:"Direct verified Mac command"});const completed=await waitForMacJob(userId,job.id);if(!completed)return{text:`I sent the command to open ${command.app}, but the Mac has not confirmed it yet.`,actions:[{tool:"mac.open_app",status:"pending",jobId:job.id}],fastPath:true};if(completed.status==="failed")return{text:`I couldn't open ${command.app}. The Mac reported: ${completed.error||"unknown error"}.`,actions:[{tool:"mac.open_app",status:"failed",jobId:job.id,error:completed.error}],fastPath:true};return{text:`${command.app} is open.`,actions:[{tool:"mac.open_app",status:"completed",jobId:job.id,result:completed.result}],fastPath:true};}
async function completeTurn({userId,sessionId,input,history=[]}){
  const fast=await tryFastMacTurn(userId,input);
  if(fast){
    Promise.all([
      appendSessionTurn({userId,sessionId,role:"user",content:input}),
      appendSessionTurn({userId,sessionId,role:"assistant",content:fast.text})
    ]).catch(error=>console.warn("Fast-turn persistence delayed:",error instanceof Error?error.message:error));
    return{...fast,responseId:null,remembered:0,memoryCount:0,webSearches:0,model:"deterministic-mac-router",engine:"v2-fast",latencyMs:0};
  }
  return completeTurnV2({userId,sessionId,input,history});
}
app.use("/api/connector",createGovernedConnectorRouter({executeCommand:({userId,sessionId,input})=>completeTurn({userId,sessionId,input,history:[]})}));
app.use("/mcp",createPortableMcpRouter({executeCommand:({userId,sessionId,input})=>completeTurn({userId,sessionId,input,history:[]}),userId:String(process.env.GEORGIE_PRIMARY_USER_ID||"primary")}));
app.get("/health",(_req,res)=>{const r=readinessSnapshot();res.json({ok:true,assistant:"Georgie",version:"2.2.1",ready:r.ready,...r.platform,neoMail:r.connections.neoMail,sierraWorkforce:r.connections.sierraWorkforce,macAgent:r.connections.macAgent,macQueue:r.connections.macQueue,liveWebResearch:r.connections.liveWebResearch,memoryStorage:r.connections.memoryStorage,operationalStorage:r.connections.operationalStorage,configured:r.connections.openAI,activationState:r.activationState,blockers:r.blockers})});
app.get("/api/intelligence-control-map",async(req,res)=>{try{res.json({ok:true,map:await intelligenceControlMapStatus(getUserId(req))})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Control Map unavailable"})}});
app.post("/api/intelligence-control-map/refresh",async(req,res)=>{try{res.json({ok:true,map:await refreshIntelligenceControlMap(getUserId(req))})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Control Map refresh failed"})}});
app.get("/api/readiness",(_req,res)=>res.json({ok:true,...readinessSnapshot()}));app.get("/api/tools",(_req,res)=>res.json({ok:true,tools:listToolDefinitions()}));app.use("/api/mac",createMacRouter());app.get("/api/mac-devices",(_req,res)=>res.json({ok:true,devices:getMacDeviceStatus()}));app.get("/api/mac-jobs",async(req,res)=>{try{res.json({ok:true,storage:macQueueStorageStatus(),jobs:await listMacJobs(getUserId(req),Number(req.query?.limit||50))})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.get("/api/mail/accounts",(_req,res)=>{try{res.json({ok:true,provider:"neo",configured:neoMailConfigured(),accounts:listNeoMailboxes()})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.post("/api/mail/verify/:id",async(req,res)=>{try{res.json({ok:true,result:await verifyNeoMailbox(req.params.id)})}catch(error){res.status(400).json({ok:false,error:error instanceof Error?error.message:"Neo Mail verification failed"})}});app.post("/api/mail/sweep",async(_req,res)=>{try{await sweepNeoMail();res.json({ok:true})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Neo Mail sweep failed"})}});
app.get("/api/profile",async(req,res)=>{try{res.json({ok:true,profile:await getProfile(getUserId(req))})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.patch("/api/profile",async(req,res)=>{try{res.json({ok:true,profile:await updateProfile(getUserId(req),req.body?.profile||req.body||{})})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.get("/api/memories",async(req,res)=>{try{const userId=getUserId(req),q=String(req.query?.q||""),memories=q?await searchMemories(userId,q,Number(req.query?.limit||50)):await listMemories(userId,Number(req.query?.limit||100));res.json({ok:true,memories})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.post("/api/memories",async(req,res)=>{try{const memory=await addMemory({userId:getUserId(req),...(req.body||{}),source:"explicit"});if(!memory)return res.status(400).json({ok:false,error:"Memory text is required"});res.status(201).json({ok:true,memory})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.delete("/api/memories/:id",async(req,res)=>{try{const removed=await deleteMemory(getUserId(req),req.params.id);res.status(removed?200:404).json({ok:removed})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});
app.get("/api/tasks",async(req,res)=>{try{res.json({ok:true,tasks:await listTasks(getUserId(req),{status:req.query?.status||"open",limit:req.query?.limit||50})})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.post("/api/tasks",async(req,res)=>{try{res.status(201).json({ok:true,task:await createTask({userId:getUserId(req),...(req.body||{}),source:"explicit"})})}catch(error){res.status(400).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.patch("/api/tasks/:id",async(req,res)=>{try{const task=await updateTask(getUserId(req),req.params.id,req.body||{});res.status(task?200:404).json({ok:Boolean(task),task})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.delete("/api/tasks/:id",async(req,res)=>{try{const removed=await deleteTask(getUserId(req),req.params.id);res.status(removed?200:404).json({ok:removed})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.get("/api/events",async(req,res)=>{try{res.json({ok:true,events:await listEvents(getUserId(req),{status:req.query?.status||"pending",limit:req.query?.limit||30})})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.post("/api/events/:id/ack",async(req,res)=>{try{const event=await acknowledgeEvent(getUserId(req),req.params.id);res.status(event?200:404).json({ok:Boolean(event),event})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.get("/api/session",async(req,res)=>{try{res.json({ok:true,history:await getSessionHistory(getUserId(req),getSessionId(req),Number(req.query?.limit||40))})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});
app.post("/api/transcribe",upload.single("audio"),async(req,res)=>{try{if(!req.file)return res.status(400).json({ok:false,error:"Audio file is required"});const text=await transcribeAudio({buffer:req.file.buffer,mimeType:req.file.mimetype,filename:req.file.originalname});res.json({ok:true,text})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.post("/api/respond",async(req,res)=>{try{const{input,history=[]}=req.body??{};if(!input?.trim())return res.status(400).json({ok:false,error:"Input is required"});const response=await completeTurn({userId:getUserId(req),sessionId:getSessionId(req),input:input.trim(),history});res.json({ok:true,...response,spokenText:spokenResponseFor(input,response.text)})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.post("/api/speak",async(req,res)=>{try{const audio=await synthesizeSpeech(req.body?.text);res.setHeader("Content-Type","audio/mpeg");res.setHeader("Cache-Control","no-store");res.send(audio)}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});app.post("/api/voice-turn",upload.single("audio"),async(req,res)=>{try{if(!req.file)return res.status(400).json({ok:false,error:"Audio file is required"});const userId=getUserId(req),sessionId=getSessionId(req),history=req.body?.history?JSON.parse(req.body.history):[],transcript=await transcribeAudio({buffer:req.file.buffer,mimeType:req.file.mimetype,filename:req.file.originalname}),response=await completeTurn({userId,sessionId,input:transcript,history}),spokenText=spokenResponseFor(transcript,response.text),speech=await synthesizeSpeech(spokenText);res.json({ok:true,transcript,text:response.text,spokenText,response,speechBase64:speech.toString("base64"),audioBase64:speech.toString("base64"),contentType:"audio/mpeg",audioMimeType:"audio/mpeg"})}catch(error){res.status(500).json({ok:false,error:error instanceof Error?error.message:"Unknown error"})}});

startCloudStateRecovery();
startMobileTurnRecovery();
startProactiveEngine();
startEmailIntelligence();
startMaintenanceSentinel();
startReconciliationWorkers();
startWorldStateSentinel();
startRevenueController();
startSelfEvolution();
startBackgroundOperatingLayer();
startIntelligenceControlMap();
startApprovalDispatchWorker();
startEngineeringCoordinator();
const PORT=Number(process.env.PORT||10000);
const server=app.listen(PORT,()=>console.log(`Georgie listening on port ${PORT}`));
attachRealtimeRelay(server);
