import crypto from "crypto";
import { readCloudState, writeCloudState } from "./cloud-state.js";
const NS="tasks";
async function readStore(userId="primary"){const s=await readCloudState(userId,NS,{tasks:[]});return{tasks:Array.isArray(s.tasks)?s.tasks:[]};}
async function writeStore(userId,store){await writeCloudState(userId,NS,store);}
export async function createTask({userId,title,notes="",dueAt=null,priority="normal",source="assistant",domain="uncertain",evidence=null}){if(!title?.trim())throw new Error("Task title is required");const uid=String(userId||"primary");const store=await readStore(uid);const task={id:crypto.randomUUID(),userId:uid,title:title.trim().slice(0,240),notes:String(notes||"").slice(0,4000),dueAt:dueAt||null,priority:["low","normal","high","urgent"].includes(priority)?priority:"normal",domain:["personal","household","sierra","uncertain"].includes(domain)?domain:"uncertain",evidence:evidence&&typeof evidence==="object"?evidence:null,status:"open",source,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),completedAt:null};store.tasks.push(task);store.tasks=store.tasks.slice(-5000);await writeStore(uid,store);return task;}
export async function listTasks(userId,{status="open",limit=50}={}){const uid=String(userId||"primary");const store=await readStore(uid);return store.tasks.filter(t=>t.userId===uid&&(status==="all"||t.status===status)).sort((a,b)=>{if(a.dueAt&&b.dueAt)return new Date(a.dueAt)-new Date(b.dueAt);if(a.dueAt)return-1;if(b.dueAt)return 1;return new Date(b.createdAt)-new Date(a.createdAt);}).slice(0,Math.max(1,Math.min(Number(limit)||50,200)));}
export async function listAllTasks({status="open",limit=1000,userId=process.env.GEORGIE_PRIMARY_USER_ID||"primary"}={}){return listTasks(userId,{status,limit});}
export async function updateTask(userId,taskId,patch={}){const uid=String(userId||"primary");const store=await readStore(uid);const task=store.tasks.find(x=>x.userId===uid&&x.id===taskId);if(!task)return null;if(patch.title!==undefined)task.title=String(patch.title).trim().slice(0,240);if(patch.notes!==undefined)task.notes=String(patch.notes||"").slice(0,4000);if(patch.dueAt!==undefined)task.dueAt=patch.dueAt||null;if(patch.priority&&["low","normal","high","urgent"].includes(patch.priority))task.priority=patch.priority;if(patch.domain&&["personal","household","sierra","uncertain"].includes(patch.domain))task.domain=patch.domain;if(patch.status&&["open","completed","cancelled"].includes(patch.status)){task.status=patch.status;task.completedAt=patch.status==="completed"?new Date().toISOString():null;}task.updatedAt=new Date().toISOString();await writeStore(uid,store);return task;}
export async function deleteTask(userId,taskId){const uid=String(userId||"primary");const store=await readStore(uid);const before=store.tasks.length;store.tasks=store.tasks.filter(t=>!(t.userId===uid&&t.id===taskId));if(store.tasks.length===before)return false;await writeStore(uid,store);return true;}
