import { searchMemories } from "./memory.js";
import { createTask, listTasks, updateTask } from "./tasks.js";
import { enqueueMacJob, listMacJobs } from "./mac/queue.js";
import { listNeoMailboxes, listRecentMessages, readMessage, searchMessages, sendMessage, verifyNeoMailbox } from "./integrations/neo-mail.js";
import { getMailboxEvidencePacket, listMailboxPacketManifests } from "./mailbox-evidence-bridge.js";
import { executeApprovedSierraChange, getSierraApplyInventory, getSierraAuditEvents, getSierraDeal, getSierraDocumentManifest, getSierraGovernedAccess, getSierraGuardedLenderConflicts, getSierraHealth, getSierraInfrastructure, getSierraLenderResponses, getSierraNetworkGaps, getSierraOffers, getSierraPortfolio, getSierraReconciliationInvariant, getSierraStrategy, queueSierraAction, sierraWorkforceConfigured } from "./integrations/sierra-workforce.js";
import { getGithubObservability, getProviderObservability, getRenderObservability, getVercelObservability } from "./integrations/provider-observability.js";
import { githubSourceConfigured, listRepositories as githubListRepositories, getRepository as githubGetRepository, listBranches as githubListBranches, getBranch as githubGetBranch, readFile as githubReadFile, searchSource as githubSearchSource, createBranch as githubCreateBranch, createFileCommit as githubCreateFileCommit, createPullRequest as githubCreatePullRequest } from "./integrations/github-source.js";
import { maintenanceStatus, runMaintenanceCycle } from "./maintenance-sentinel.js";
import { diagnoseSmartleadCampaigns, getSmartleadCampaigns, updateSmartleadCampaignStatus } from "./integrations/smartlead.js";
import { evaluationScorecard } from "./evaluation.js";
import { decideApproval, listApprovals, listDecisions, recordDecision } from "./command-layer.js";
import { getMacDeviceStatus } from "./mac/router.js";
import { resourceGovernorStatus } from "./resource-governor.js";
import { getCapabilityManifest } from "./capability-manifest.js";
import { listActionJournal, recordAction } from "./action-journal.js";
import { reconciliationStatus, runReconciliationCycle } from "./reconciliation-workers.js";
import { listDomainPacks } from "./domain-packs.js";
import { buildWorldState } from "./world-state.js";
import { readWorldStateSnapshot, refreshWorldState } from "./world-state-sentinel.js";
import { runStaticBenchmark } from "./intelligence-benchmark.js";
import { runSelfEvolutionCycle, selfEvolutionStatus } from "./self-evolution.js";
import { activateBackgroundOperatingLayer, backgroundOperatingStatus, runBackgroundOperatingCycle } from "./background-operating-layer.js";
import { intelligenceControlMapStatus, refreshIntelligenceControlMap } from "./intelligence-control-map.js";
import { createApprovalRequest, getApprovalRequest } from "./command-layer.js";
import { createEnrollmentCode } from "./mobile-auth.js";
import { operatingContinuity, transitionOperatingNode, upsertOperatingNode } from "./operating-graph.js";
import { approvePlanById, listApprovalPlans, listRecoverableApprovalDispatches, preflightExecution, prepareApprovalPlan, recordApprovalDispatch, resolveConversationalApproval, transitionApprovalPlan } from "./approval-continuation.js";
import { engineeringCoordinatorStatus, runEngineeringCoordinatorCycle, seedMissionWork } from "./engineering-coordinator.js";
import { autonomousRepairPolicy, enqueueHandoff, listHandoffs, missionStatus } from "./shared-mission.js";
import { eliteTaskContract, startEliteTask, verifyEliteTask } from "./elite-task-kernel.js";
import { buildDealEvidenceGraph, normalizeGuardedConflicts } from "./evidence-foundation.js";
import { continueDurableDiagnosticPlan, listDiagnosticPlans, runDurableDiagnosticPlan } from "./diagnostic-plans.js";
import { getDealWorkspace, listDealWorkspaces, refreshDealWorkspace } from "./deal-workspaces.js";
import { buildDocumentIntelligence } from "./document-intelligence.js";
import { certifyDocumentIntelligence } from "./document-certification.js";
import crypto from "crypto";
import { verifyBusinessOutcome } from "./outcome-verification.js";
import { checkpointReportDelivery, investigationArtifactPage, listInvestigationArtifacts, openInvestigationArtifact, persistInvestigationArtifact } from "./investigation-artifacts.js";
import { activateRevenueController, revenueControllerStatus } from "./revenue-controller.js";
import { phase2Foundation } from "./phase2-foundation.js";
import { validateBrowserWorkflow } from "./browser-workflow.js";
import { readSeoPhase2PublicState, verifySeoPhase2PublicState } from "./seo-phase2-public.js";
import { executeInfrastructureAdmin } from "./integrations/infrastructure-admin.js";

const LEVELS={read:0,low_risk_write:1,sensitive_write:2,external_side_effect:3};const registry=new Map();function defineTool(definition){registry.set(definition.name,definition)}
defineTool({name:"infrastructure_admin.vercel_team_members_list",description:"List members of the configured Vercel team through the governed infrastructure-admin adapter.",risk:"read",async run({userId,args}){return executeInfrastructureAdmin(userId,{action:"vercel.team.members.list",tenant:args?.teamId||args?.tenant,requester:args?.requester||"georgie",idempotencyKey:args?._governance?.idempotencyKey})}});
defineTool({name:"infrastructure_admin.vercel_team_member_verify",description:"Verify one exact Vercel team member email and role using a fresh provider member-list read.",risk:"read",async run({userId,args}){const email=String(args?.email||args?.subject||"").trim().toLowerCase(),requestedRole=String(args?.role||"DEVELOPER").trim().toUpperCase();if(!email)throw new Error("Vercel member verification requires an email");const listed=await executeInfrastructureAdmin(userId,{action:"vercel.team.members.list",tenant:args?.teamId||args?.tenant,requester:args?.requester||"georgie"});const payload=listed?.result;const members=Array.isArray(payload)?payload:Array.isArray(payload?.members)?payload.members:Array.isArray(payload?.data)?payload.data:[];const match=members.find(item=>String(item?.email||item?.user?.email||item?.member?.email||"").trim().toLowerCase()===email)||null;const actualRole=String(match?.role||match?.teamRole||match?.membership?.role||"").trim().toUpperCase()||null;return{verified:Boolean(match)&&actualRole===requestedRole,email,role:actualRole,requestedRole,member:match?{uid:match?.uid||match?.id||match?.user?.uid||match?.user?.id||null,email,role:actualRole}:null,checkedAt:new Date().toISOString()}}});
defineTool({name:"infrastructure_admin.vercel_team_member_invite",description:"Invite a person to the configured Vercel team. This is an external side effect and requires an approved governance receipt.",risk:"external_side_effect",async run({userId,args}){const approvalId=args?._governance?.approvalId||args?.approvalId;if(!approvalId)throw new Error("Vercel member invitation requires an approved governance receipt");return executeInfrastructureAdmin(userId,{action:"vercel.team.member.invite",tenant:args?.teamId||args?.tenant,subject:args?.email||args?.subject,role:args?.role||"DEVELOPER",approved:true,approvalId,requester:args?.requester||"georgie",idempotencyKey:args?._governance?.idempotencyKey})}});
defineTool({name:"infrastructure_admin.supabase_organization_members_list",description:"List members of the configured Supabase organization through the governed infrastructure-admin adapter.",risk:"read",async run({userId,args}){return executeInfrastructureAdmin(userId,{action:"supabase.organization.members.list",tenant:args?.organizationSlug||args?.tenant,requester:args?.requester||"georgie",idempotencyKey:args?._governance?.idempotencyKey})}});
defineTool({name:"infrastructure_admin.supabase_organization_member_invite",description:"Invite a person to the configured Supabase organization through the official API when available, otherwise return the governed dashboard-fallback requirement. Requires an approved governance receipt.",risk:"external_side_effect",async run({userId,args}){const approvalId=args?._governance?.approvalId||args?.approvalId;if(!approvalId)throw new Error("Supabase member invitation requires an approved governance receipt");return executeInfrastructureAdmin(userId,{action:"supabase.organization.member.invite",tenant:args?.organizationSlug||args?.tenant,subject:args?.email||args?.subject,role:args?.role||"DEVELOPER",approved:true,approvalId,requester:args?.requester||"georgie",idempotencyKey:args?._governance?.idempotencyKey})}});

defineTool({name:"memory.search",description:"Search Georgie's durable memory for relevant user context.",risk:"read",async run({userId,args}){return searchMemories(userId,String(args?.query||""),Number(args?.limit||8))}});
defineTool({name:"tasks.list",description:"List the user's open, completed, or all tasks.",risk:"read",async run({userId,args}){return listTasks(userId,{status:args?.status||"open",limit:args?.limit||30})}});
defineTool({name:"tasks.create",description:"Create a task for the user.",risk:"low_risk_write",async run({userId,args}){return createTask({userId,...(args||{}),source:"georgie-tool"})}});
defineTool({name:"tasks.update",description:"Update, complete, or cancel a task.",risk:"low_risk_write",async run({userId,args}){return updateTask(userId,args?.taskId,args?.patch||{})}});
function queueMac(userId,args,action,risk,reason,payload={}){const governance=args?._governance||{};return enqueueMacJob({userId,deviceId:args?.deviceId||"primary-mac",action,args:payload,risk,reason,idempotencyKey:governance.idempotencyKey,approvalId:governance.approvalId,planId:governance.planId})}
const SYNCHRONOUS_TOOL_BUDGET_MS=Math.max(5000,Math.min(15000,Number(process.env.GEORGIE_TOOL_WAIT_MS||12000)));
async function queueMacAndWait(userId,args,action,risk,reason,payload={},timeoutMs=SYNCHRONOUS_TOOL_BUDGET_MS){const job=await queueMac(userId,args,action,risk,reason,payload);const boundedTimeout=Math.max(1000,Math.min(SYNCHRONOUS_TOOL_BUDGET_MS,Number(timeoutMs)||SYNCHRONOUS_TOOL_BUDGET_MS));const deadline=Date.now()+boundedTimeout;while(Date.now()<deadline){const current=(await listMacJobs(userId,100)).find(item=>item.id===job.id);if(current&&["completed","failed"].includes(current.status)){if(current.status==="failed")throw new Error(current.error||`${action} failed`);return current;}await new Promise(resolve=>setTimeout(resolve,300));}return{...job,status:"pending",durable:true,verification:`Mac agent did not confirm within the ${boundedTimeout}ms synchronous budget; the durable job remains available for later verification`};}
defineTool({name:"seo.discovery_baseline",description:"Run a bounded read-only Sierra website crawl for the durable SEO worker.",risk:"read",async run({args}){const integration=seoIntegrationStatus();return crawlWebsite({startUrl:integration.websiteRoot,maxPages:Math.max(1,Math.min(Number(args?.maxPages||150),500))})}});
defineTool({name:"seo.wordpress_link_integrity_repair",description:"Execute the exact reversible Sierra WordPress link-integrity batch through the governed Mac session. The Mac handler backs up every matched record and rolls back automatically if verification fails.",risk:"low_risk_write",async run({userId,args}){if(String(args?.siteOrigin||"").replace(/\/$/,"")!=="https://sierramarketinginc.com"||args?.authority!=="reversible_write")throw new Error("SEO_LINK_REPAIR_SCOPE_REJECTED");return queueMacAndWait(userId,args,"browser.wordpress_link_integrity_repair","low_risk_write","Exact reversible WordPress link-integrity repair",{siteOrigin:"https://sierramarketinginc.com",authority:"reversible_write",operation:"repair_link_integrity"},45000)}});
defineTool({name:"seo.wordpress_link_integrity_verify",description:"Verify by fresh crawl that the known broken internal link and malformed submissions email URL no longer occur.",risk:"read",async run({args}){const integration=seoIntegrationStatus(),crawl=await crawlWebsite({startUrl:integration.websiteRoot,maxPages:Math.max(1,Math.min(Number(args?.maxPages||150),500))});const brokenTarget=crawl.pages.some(page=>String(page.url||"").includes("/sba-bank-term-loans-for-businesses/")&&Number(page.status)>=400),malformedEmail=crawl.pages.some(page=>/^http:\/\/submissions@sierramarketinginc\.com/i.test(String(page.url||"")));return{verified:!brokenTarget&&!malformedEmail,brokenTarget,malformedEmail,crawledAt:crawl.crawledAt,pageCount:crawl.pageCount}}});
defineTool({name:"seo.phase2_before_state",description:"Capture immutable public before-state for one allowlisted Sierra SEO Phase 2 batch.",risk:"read",async run({args}){if(String(args?.siteOrigin||"").replace(/\/$/,"")!=="https://sierramarketinginc.com")throw new Error("SEO_PHASE2_BEFORE_SITE_REJECTED");const state=await readSeoPhase2PublicState({pages:args?.pages||[]});return{commandId:args?.commandId||null,batch:args?.batch||null,planHash:args?.planHash||null,beforeStateCaptured:true,productionMutation:false,observedAt:state.observedAt,pages:state.pages.map(page=>({pathname:page.pathname,status:page.status,title:page.title,h1:page.h1,h1Count:page.h1Count,structuredDataCount:page.structuredDataCount,htmlHash:page.htmlHash,bodyTextHash:page.bodyTextHash}))}}});
defineTool({name:"seo.phase2_batch_execute",description:"Execute exactly one compiled allowlisted Sierra SEO Phase 2 batch through primary-mac. The Mac independently validates command, batch, page scope, plan fingerprint, protected surfaces, and duplicate replay before any WordPress write.",risk:"low_risk_write",async run({userId,args}){if(String(args?.siteOrigin||"").replace(/\/$/,"")!=="https://sierramarketinginc.com"||args?.authority!=="reversible_write")throw new Error("SEO_PHASE2_EXECUTION_SCOPE_REJECTED");return queueMacAndWait(userId,args,"browser.wordpress_phase2_batch","low_risk_write","Execute exact compiled Sierra SEO Phase 2 WordPress batch",{siteOrigin:"https://sierramarketinginc.com",authority:"reversible_write",operation:"execute_phase2_batch",commandId:args?.commandId,batch:args?.batch,planHash:args?.planHash,pages:args?.pages||[],changeClasses:args?.changeClasses||[],protectedSurfaces:args?.protectedSurfaces||[]},45000)}});
defineTool({name:"seo.phase2_batch_verify",description:"Semantically verify one Sierra SEO Phase 2 batch against fresh public HTML. A failed public predicate triggers bounded primary-mac rollback of that exact command/plan before returning failure.",risk:"read",async run({userId,args}){const verification=await verifySeoPhase2PublicState({batch:args?.batch,pages:args?.pages||[],planHash:args?.planHash});if(verification.verified===true)return verification;let rollback=null;try{rollback=await queueMacAndWait(userId,args,"browser.wordpress_phase2_rollback","low_risk_write","Rollback exact Sierra SEO Phase 2 batch after failed public semantic verification",{siteOrigin:"https://sierramarketinginc.com",authority:"reversible_write",operation:"rollback_phase2_batch",commandId:args?.commandId,batch:args?.batch,planHash:args?.planHash},45000)}catch(error){rollback={status:"failed",error:error instanceof Error?error.message:String(error)}}return{...verification,rollbackAttempted:true,rollback}}});
defineTool({name:"seo.phase2_after_state",description:"Capture immutable public after-state for one allowlisted Sierra SEO Phase 2 batch.",risk:"read",async run({args}){if(String(args?.siteOrigin||"").replace(/\/$/,"")!=="https://sierramarketinginc.com")throw new Error("SEO_PHASE2_AFTER_SITE_REJECTED");const state=await readSeoPhase2PublicState({pages:args?.pages||[]});return{commandId:args?.commandId||null,batch:args?.batch||null,planHash:args?.planHash||null,publicReadbackVerified:true,productionMutation:false,observedAt:state.observedAt,pages:state.pages.map(page=>({pathname:page.pathname,status:page.status,title:page.title,h1:page.h1,h1Count:page.h1Count,structuredDataCount:page.structuredDataCount,htmlHash:page.htmlHash,bodyTextHash:page.bodyTextHash}))}}});
defineTool({name:"mac.jobs",description:"List recent jobs executed or queued for the user's Georgie Mac Agent.",risk:"read",async run({userId,args}){return listMacJobs(userId,Number(args?.limit||30))}});
defineTool({name:"mac.devices",description:"Read connected Mac Agent heartbeat status and verify whether each approved Mac is currently online.",risk:"read",async run(){return getMacDeviceStatus()}});
defineTool({name:"mac.system_info",description:"Ask the connected Mac for hostname, architecture, OS release and uptime.",risk:"read",async run({userId,args}){return queueMac(userId,args,"system.info","read","System status requested by Georgie")}});
defineTool({name:"mac.clipboard_read",description:"Read text currently on the connected Mac clipboard.",risk:"read",async run({userId,args}){return queueMac(userId,args,"clipboard.read","read","Clipboard requested by Georgie")}});
defineTool({name:"mac.file_read",description:"Read a text file from the connected Mac Desktop, Documents, or Downloads folder.",risk:"read",async run({userId,args}){return queueMac(userId,args,"file.read","read","File requested by Georgie",{path:args?.path})}});
defineTool({name:"mac.open_app",description:"Open an allowlisted application on the connected Mac.",risk:"low_risk_write",async run({userId,args}){return queueMac(userId,args,"app.open","low_risk_write","Application launch requested by Georgie",{app:args?.app})}});
defineTool({name:"mac.activate_app",description:"Bring an allowlisted application to the foreground on the connected Mac.",risk:"low_risk_write",async run({userId,args}){return queueMac(userId,args,"app.activate","low_risk_write","Application activation requested by Georgie",{app:args?.app})}});
defineTool({name:"mac.open_url",description:"Open an HTTP or HTTPS URL on the connected Mac.",risk:"low_risk_write",async run({userId,args}){return queueMac(userId,args,"url.open","low_risk_write","Web page requested by Georgie",{url:args?.url})}});
defineTool({name:"mac.clipboard_write",description:"Put text onto the connected Mac clipboard.",risk:"low_risk_write",async run({userId,args}){return queueMac(userId,args,"clipboard.write","low_risk_write","Clipboard update requested by Georgie",{text:args?.text})}});
defineTool({name:"mac.notification",description:"Show a local notification on the connected Mac.",risk:"low_risk_write",async run({userId,args}){return queueMac(userId,args,"notification.show","low_risk_write","Notification requested by Georgie",{title:args?.title,body:args?.body})}});
defineTool({name:"mac.screen_capture",description:"Capture the connected Mac's current screen for visual understanding. Requires sensitive authorization because the screen may contain private information.",risk:"sensitive_write",async run({userId,args}){return queueMac(userId,args,"screen.capture","sensitive_write","Screen capture requested by Georgie")}});
defineTool({name:"mac.browser_inspect",description:"Enumerate Safari and Chrome windows and tabs, identify active tabs, and inspect page text only on approved Sierra operating domains. Never captures password or form values. Requires explicit sensitive authorization.",risk:"sensitive_write",async run({userId,args}){return queueMacAndWait(userId,args,"browser.inspect_tabs","sensitive_write","Explicit browser-tab operating review requested by the user",{includeContent:args?.includeContent!==false},45000)}});
defineTool({name:"mac.click",description:"Click an explicit screen coordinate through macOS Accessibility. Requires sensitive authorization and returns acceptance evidence, not proof of the resulting application state.",risk:"sensitive_write",async run({userId,args}){return queueMacAndWait(userId,args,"ui.click","sensitive_write","Explicit coordinate click requested by the user",{x:args?.x,y:args?.y},15000)}});
defineTool({name:"mac.type_text",description:"Type text into the currently focused Mac application. Requires sensitive authorization because it changes application state.",risk:"sensitive_write",async run({userId,args}){return queueMac(userId,args,"ui.type_text","sensitive_write","UI text entry requested by Georgie",{text:args?.text})}});
defineTool({name:"mac.key",description:"Send an allowlisted navigation or editing key to the currently focused Mac application, optionally with command/option/control/shift modifiers.",risk:"sensitive_write",async run({userId,args}){return queueMac(userId,args,"ui.key","sensitive_write","UI key command requested by Georgie",{key:args?.key,modifiers:args?.modifiers})}});
defineTool({name:"mac.browser_workflow",description:"Execute one approval-bound, resumable semantic browser workflow against one allowlisted Supabase project and setting set. Every step is checkpointed and ambiguity fails closed.",risk:"sensitive_write",async run({userId,args}){const workflow=validateBrowserWorkflow(args?.workflow||{});return queueMac(userId,args,"browser.workflow","sensitive_write","Exact approved semantic browser workflow",{workflow})}});
defineTool({name:"developer.repo_inspect",description:"Inspect an allowlisted Git repository on the connected Mac: branch, working-tree status, recent commits, and tracked files. Read-only. Returns a durable pending job before the turn deadline when the Mac is slow.",risk:"read",async run({userId,args}){return queueMacAndWait(userId,args,"developer.repo_inspect","read","Repository inspection requested by Georgie",{repo:args?.repo},8000)}});
defineTool({name:"developer.search",description:"Search source text inside an allowlisted Git repository. Excludes Git internals, dependencies, and environment-secret files. Read-only. Returns a durable pending job instead of blocking the turn when the Mac is slow.",risk:"read",async run({userId,args}){return queueMacAndWait(userId,args,"developer.search","read","Repository code search requested by Georgie",{repo:args?.repo,query:args?.query})}});
defineTool({name:"developer.file_read",description:"Read one source file inside an allowlisted Git repository. Secret and generated paths are denied. Read-only. Returns a durable pending job instead of blocking the turn when the Mac is slow.",risk:"read",async run({userId,args}){return queueMacAndWait(userId,args,"developer.file_read","read","Repository source file requested by Georgie",{repo:args?.repo,path:args?.path})}});
defineTool({name:"developer.prepare_patch",description:"Prepare a governed code patch for an allowlisted repository. Stores an approval request bound to the exact repository and SHA-256 patch hash; it does not change code.",risk:"low_risk_write",async run({userId,args}){const repo=String(args?.repo||"").trim(),patch=String(args?.patch||"");if(!repo||!patch)throw new Error("Repository and unified patch are required");if(patch.length>100000)throw new Error("Patch exceeds 100,000 characters");const patchHash=crypto.createHash("sha256").update(patch).digest("hex");return createApprovalRequest(userId,{domain:"technical",actionType:"developer_apply_patch",title:args?.title||"Apply prepared code patch",summary:args?.summary||"Georgie prepared a repository patch for review and approval.",evidence:{repo,patch,patchHash},risk:"high",reversible:true,verificationMethod:args?.verificationMethod||"Run repository checks and inspect git diff after application.",rollbackPlan:"Reverse the exact patch or restore affected files from version control after explicit approval."})}});
defineTool({name:"developer.apply_approved_patch",description:"Apply one previously approved developer patch to its exact allowlisted repository. Approval must match the stored SHA-256 patch hash. Does not commit, push, or deploy.",risk:"sensitive_write",async run({userId,args}){const approval=await getApprovalRequest(userId,args?.approvalId);if(!approval)throw new Error("Developer patch approval was not found");if(approval.actionType!=="developer_apply_patch")throw new Error("Approval is not for a developer patch");if(approval.status!=="approved")throw new Error("Developer patch has not been approved");const {repo,patch,patchHash}=approval.evidence||{};const actual=crypto.createHash("sha256").update(String(patch||"")).digest("hex");if(!patchHash||actual!==patchHash)throw new Error("Approved patch integrity check failed");return queueMacAndWait(userId,args,"developer.apply_patch","sensitive_write","Exact approved developer patch",{repo,patch,patchHash},60000)}});
defineTool({name:"developer.run_checks",description:"Run only an allowlisted repository package script (check, test, or benchmark) on the connected Mac and return bounded verification output.",risk:"sensitive_write",async run({userId,args}){return queueMacAndWait(userId,args,"developer.run_checks","sensitive_write","Explicit repository verification requested by the user",{repo:args?.repo,script:args?.script||"check"},130000)}});
defineTool({name:"email.accounts",description:"List the user's configured Neo Mail mailboxes and their business roles.",risk:"read",async run(){return listNeoMailboxes()}});
defineTool({name:"email.verify",description:"Verify secure IMAP and SMTP connectivity for a configured Neo Mail mailbox.",risk:"read",async run({args}){return verifyNeoMailbox(args?.mailboxId)}});
defineTool({name:"email.list",description:"List recent Neo Mail inbox messages without changing mailbox state. Supports unseen-only filtering.",risk:"read",async run({args}){return listRecentMessages(args?.mailboxId,{limit:args?.limit||20,unseenOnly:Boolean(args?.unseenOnly)})}});
defineTool({name:"email.read_only_list",description:"Governed read-only listing for a configured Neo Mail inbox. Never sends, flags, moves, deletes, or changes read state.",risk:"read",async run({args}){return listRecentMessages(args?.mailboxId,{limit:Math.min(100,Math.max(1,Number(args?.limit||25))),unseenOnly:Boolean(args?.unseenOnly)})}});
defineTool({name:"email.search",description:"Search a Neo Mail mailbox by sender, recipient, subject, or message body without changing mailbox state.",risk:"read",async run({args}){return searchMessages(args?.mailboxId,{query:args?.query||"",limit:args?.limit||25})}});
defineTool({name:"email.read",description:"Read one Neo Mail message without changing read state. markSeen is permanently forced false.",risk:"read",async run({args}){return readMessage(args?.mailboxId,args?.uid,{markSeen:false})}});
defineTool({name:"email.read_only_message",description:"Governed read-only retrieval of one configured Neo Mail message. markSeen is permanently false; sending and mailbox mutations are unavailable.",risk:"read",async run({args}){return readMessage(args?.mailboxId,args?.uid,{markSeen:false})}});
defineTool({name:"mailbox.evidence_manifests",description:"List redacted governed packet manifests for one exact mailbox-evidence objective. Does not search or export a mailbox.",risk:"read",async run({userId,args}){if(!args?.objectiveId)throw new Error("objectiveId required");return listMailboxPacketManifests(userId,args)}});
defineTool({name:"mailbox.evidence_packet",description:"Retrieve one redacted governed mailbox evidence packet by objective ID and packet ID. Does not expose arbitrary mailbox access.",risk:"read",async run({userId,args}){if(!args?.objectiveId||!args?.packetId)throw new Error("objectiveId and packetId required");return getMailboxEvidencePacket(userId,args)}});
defineTool({name:"email.send",description:"Send one policy-enforced, idempotent email through Neo Mail. Requires rationale, authoritative evidence state, and an idempotency key.",risk:"external_side_effect",async run({args}){return sendMessage(args?.mailboxId,{to:args?.to,cc:args?.cc,bcc:args?.bcc,subject:args?.subject,text:args?.text,html:args?.html,replyTo:args?.replyTo,idempotencyKey:args?._governance?.idempotencyKey||args?.idempotencyKey,correlationId:args?.correlationId,dealId:args?.dealId,threadId:args?.threadId,audience:args?.audience,rationale:args?.rationale,evidenceState:args?.evidenceState,escalation:args?.escalation})}});
defineTool({name:"github.repository.list",description:"List allowlisted repositories through authenticated server-side GitHub access. Never uses the Mac agent or public-web fallback.",risk:"read",async run(){return githubListRepositories()}});
defineTool({name:"github.repository.get",description:"Read metadata for one allowlisted repository through authenticated server-side GitHub access.",risk:"read",async run({args}){return githubGetRepository(args?.repository)}});
defineTool({name:"github.branch.list",description:"List branches and exact head SHAs for one allowlisted repository through authenticated server-side GitHub access.",risk:"read",async run({args}){return githubListBranches(args?.repository)}});
defineTool({name:"github.branch.get",description:"Read one branch and exact head SHA through authenticated server-side GitHub access.",risk:"read",async run({args}){return githubGetBranch(args?.repository,args?.branch||"main")}});
defineTool({name:"github.file.read",description:"Read a non-secret source file from an allowlisted repository through authenticated server-side GitHub access.",risk:"read",async run({args}){return githubReadFile(args?.repository,args?.path,args?.ref||"main")}});
defineTool({name:"github.source.search",description:"Search source in an allowlisted repository through authenticated server-side GitHub access.",risk:"read",async run({args}){return githubSearchSource(args?.repository,args?.query)}});
defineTool({name:"github.branch.create",description:"Create a branch in an allowlisted repository. Governed write; never falls back to Mac or public web.",risk:"sensitive_write",async run({args}){return githubCreateBranch(args?.repository,args?.branch,args?.baseRef||"main")}});
defineTool({name:"github.commit.create",description:"Create or update one source file as a GitHub commit on an existing branch. Governed write requiring approval.",risk:"sensitive_write",async run({args}){return githubCreateFileCommit(args?.repository,args||{})}});
defineTool({name:"github.pull_request.create",description:"Open a pull request in an allowlisted repository. Governed write requiring approval.",risk:"sensitive_write",async run({args}){return githubCreatePullRequest(args?.repository,args||{})}});
const workforceOnly=true;
defineTool({name:"sierra.portfolio",workforceOnly,description:"Read Sierra's canonical CRM portfolio, prioritized by operational attention, including pipeline, underwriting, evidence, exceptions, lender activity, offers and closing status.",risk:"read",async run({userId,args}){return getSierraPortfolio(userId,{limit:args?.limit||25})}});
defineTool({name:"sierra.deal",workforceOnly,description:"Read the complete canonical Sierra CRM workspace for one deal by SCA reference number or referral ID.",risk:"read",async run({userId,args}){return getSierraDeal(userId,args?.reference||args?.referenceNumber||args?.id)}});
defineTool({name:"sierra.health",workforceOnly,description:"Read Sierra's latest operations-health snapshot including pipeline failures, lender delivery, evidence and recovery status.",risk:"read",async run({userId}){return getSierraHealth(userId)}});
defineTool({name:"sierra.infrastructure",workforceOnly,description:"Read Sierra's governed infrastructure, auth, worker and integration health: recovery cron spine, automation backlog, invariant violations, failed pipeline stages, correspondence leases, dead-letter recovery, management-query pressure, CapitalApply fast-path health, aggregate auth activity, worker queues and registered connection status.",risk:"read",async run({userId}){return getSierraInfrastructure(userId)}});
defineTool({name:"sierra.governed_access",workforceOnly,description:"Probe and report Georgie's actual read-first Sierra, Apply, audit, document, runtime, and reconciliation capability surface without claiming unavailable access.",risk:"read",async run({userId}){return getSierraGovernedAccess(userId)}});
defineTool({name:"sierra.apply_inventory",workforceOnly,description:"Read Apply and CapitalApply submission inventory, identifiers, timestamps, statuses, and event-linked state through the governed Sierra contract.",risk:"read",async run({userId,args}){return getSierraApplyInventory(userId,args||{})}});
defineTool({name:"sierra.audit_events",workforceOnly,description:"Read provenance-preserving Sierra audit events for a deal or the bounded operating window.",risk:"read",async run({userId,args}){return getSierraAuditEvents(userId,args||{})}});
defineTool({name:"sierra.document_manifest",workforceOnly,description:"Read document locations, hashes, preservation state, permissions, and links for one Sierra deal or Apply submission.",risk:"read",async run({userId,args}){return getSierraDocumentManifest(userId,args||{})}});
defineTool({name:"sierra.reconciliation_invariant",workforceOnly,description:"Verify that every Apply submission resolves to exactly one Sierra deal, confirmed duplicate, or quarantine record.",risk:"read",async run({userId,args}){return getSierraReconciliationInvariant(userId,args||{})}});
defineTool({name:"sierra.guarded_lender_conflicts",workforceOnly,description:"Read record-level guarded lender-activity conflicts, including affected deal, underwriting evidence, lender records, timestamps, provenance, authority boundaries, and operational impact. This contract cannot reconcile or mutate records.",risk:"read",async run({userId,args}){return getSierraGuardedLenderConflicts(userId,args||{})}});
defineTool({name:"sierra.guarded_conflict_intelligence",workforceOnly,description:"Return a normalized, record-level guarded-conflict contract preserving affected deal, workflow stage, both evidence records, provenance, field differences, authority policy, impact, recommendation, audit trail, and explicit unknowns. Read-only.",risk:"read",async run({userId,args}){const raw=await getSierraGuardedLenderConflicts(userId,args||{});return normalizeGuardedConflicts(raw,{reference:args?.reference||null})}});
defineTool({name:"sierra.prepare_change",workforceOnly,description:"Prepare a versioned Sierra production change for explicit approval, including impact, verification, rollback, provenance, and idempotency requirements. Does not execute it.",risk:"low_risk_write",async run({userId,args}){return createApprovalRequest(userId,{domain:"sierra",actionType:args?.actionType,title:args?.title||"Sierra governed production change",summary:args?.summary,evidence:args?.evidence,risk:args?.risk||"high",reversible:Boolean(args?.reversible),verificationMethod:args?.verificationMethod,rollbackPlan:args?.rollbackPlan})}});
defineTool({name:"sierra.execute_approved_change",workforceOnly,description:"Execute one previously approved Sierra change using its approval ID, explicit idempotency key, provenance, bounded payload, and post-change verification contract.",risk:"external_side_effect",async run({userId,args}){const approval=await getApprovalRequest(userId,args?.approvalId);if(!approval||approval.status!=="approved")throw new Error("An approved Sierra change request is required");if(approval.actionType!==String(args?.actionType||""))throw new Error("Approved action type does not match requested execution");if(!String(args?.idempotencyKey||"").trim())throw new Error("Idempotency key is required");return executeApprovedSierraChange(userId,args||{})}});
defineTool({name:"sierra.strategy",workforceOnly,description:"Read Sierra's prioritized company-evolution and strategic intelligence recommendations, ranked by impact, evidence, confidence, effort and risk.",risk:"read",async run({userId}){return getSierraStrategy(userId)}});
defineTool({name:"sierra.network_gaps",workforceOnly,description:"Read financing-product gaps in Sierra's lender network plus verified external lender candidates and partnership-outreach status.",risk:"read",async run({userId}){return getSierraNetworkGaps(userId)}});
defineTool({name:"sierra.lenders",workforceOnly,description:"Read lender placements, response timing, follow-up state, requests and communication activity for a Sierra deal.",risk:"read",async run({userId,args}){return getSierraLenderResponses(userId,args?.reference||args?.referenceNumber)}});
defineTool({name:"sierra.offers",workforceOnly,description:"Read and compare normalized financing offers for a Sierra deal, including payment burden, net proceeds, economics confidence and ranking.",risk:"read",async run({userId,args}){return getSierraOffers(userId,args?.reference||args?.referenceNumber)}});
defineTool({name:"sierra.evidence_graph",workforceOnly,description:"Reconstruct a complete ten-stage deal evidence graph from lead through CRM/accounting with stable record IDs, states, timestamps, provenance, confidence, contradictions, freshness, and explicit unknowns. Read-only.",risk:"read",async run({userId,args}){const reference=args?.reference||args?.referenceNumber;if(!reference)throw new Error("A Sierra deal reference is required");const settled=await Promise.allSettled([getSierraDeal(userId,reference),getSierraApplyInventory(userId,{limit:100,status:"all"}),getSierraDocumentManifest(userId,{reference}),getSierraAuditEvents(userId,{reference,limit:200}),getSierraLenderResponses(userId,reference),getSierraOffers(userId,reference),getSierraReconciliationInvariant(userId,{limit:250}),getSierraGuardedLenderConflicts(userId,{reference,limit:50})]);const names=["deal","applyInventory","documentManifest","auditEvents","lenderResponses","offers","reconciliation","guardedConflicts"],sources={};settled.forEach((item,index)=>{sources[names[index]]=item.status==="fulfilled"?item.value:{unavailable:true,error:item.reason instanceof Error?item.reason.message:String(item.reason)}});sources.guardedConflicts=normalizeGuardedConflicts(sources.guardedConflicts,{reference});return buildDealEvidenceGraph({reference,sources})}});
defineTool({name:"sierra.evidence_chain",workforceOnly,description:"Compatibility alias for Georgie's complete ten-stage deal evidence graph.",risk:"read",async run({userId,args}){return registry.get("sierra.evidence_graph").run({userId,args})}});
defineTool({name:"sierra.document_intelligence",workforceOnly,description:"Return read-only, page-cited application and bank-statement intelligence: required fields, protected identity presence, statement coverage, financial metrics, conflicts, confidence, missing evidence, and source provenance.",risk:"read",async run({userId,args}){const reference=args?.reference||args?.referenceNumber||args?.id;if(!reference)throw new Error("A Sierra deal or application reference is required");const [manifest,deal,auditEvents]=await Promise.all([getSierraDocumentManifest(userId,{reference}),getSierraDeal(userId,reference),getSierraAuditEvents(userId,{reference,limit:200})]);return buildDocumentIntelligence({reference,manifest,deal,auditEvents})}});
defineTool({name:"sierra.document_certification",workforceOnly,description:"Run the fail-closed, read-only document certification: canonical inventory, privacy-safe page citations, complete statement metrics, contradiction/unknown register, Ready/Blocked/Next Action, durable workspace read-back, and an independent second read.",risk:"read",async run({userId,args}){const reference=args?.reference||args?.referenceNumber||args?.id;if(!reference)throw new Error("A Sierra deal or application reference is required");const [intelligence,graph,tasks,approvals]=await Promise.all([registry.get("sierra.document_intelligence").run({userId,args:{reference}}),registry.get("sierra.evidence_graph").run({userId,args:{reference}}),listTasks(userId,{status:"open",limit:200}),listApprovals(userId,{status:"pending",limit:200})]);return certifyDocumentIntelligence({userId,reference,intelligence,graph,tasks,approvals})}});
defineTool({name:"sierra.deal_workspace",workforceOnly,description:"Open or refresh one persistent Deal Intelligence Workspace with page-cited documents, current stage, blockers, underwriting evidence, lender fit, conflicts, approvals, tasks, next action, and a source-linked timeline.",risk:"read",async run({userId,args}){const reference=args?.reference||args?.referenceNumber||args?.id;if(!reference)throw new Error("A Sierra deal or application reference is required");if(args?.refresh===false){const stored=await getDealWorkspace(userId,reference);if(stored)return stored;}const [graph,documentIntelligence,tasks,approvals]=await Promise.all([registry.get("sierra.evidence_graph").run({userId,args:{reference}}),registry.get("sierra.document_intelligence").run({userId,args:{reference}}),listTasks(userId,{status:"open",limit:200}),listApprovals(userId,{status:"pending",limit:200})]);return refreshDealWorkspace(userId,{reference,graph,documentIntelligence,tasks,approvals})}});
defineTool({name:"sierra.deal_workspaces",workforceOnly,description:"List Georgie's persistent, Sierra-scoped Deal Intelligence Workspaces without refreshing live systems.",risk:"read",async run({userId,args}){return listDealWorkspaces(userId,{limit:args?.limit||50})}});
defineTool({name:"sierra.diagnostic_investigations",workforceOnly,description:"List durable Sierra diagnostic investigations, their request IDs, independent step outcomes, evidence gaps, contradictions, and synthesized status.",risk:"read",async run({userId,args}){return listDiagnosticPlans(userId,args||{})}});
defineTool({name:"sierra.investigation_artifacts",workforceOnly,description:"List durable Sierra investigation evidence artifacts and their distinct execution, persistence, generation, and delivery lifecycle states.",risk:"read",async run({userId,args}){return listInvestigationArtifacts(userId,args||{})}});
defineTool({name:"sierra.investigation_open",workforceOnly,description:"Open one durable investigation by exact ID as a compact cursor-addressable report page. Raw evidence is excluded by default and available only through an explicit contract cursor, preventing oversized turns and enabling resumable delivery.",risk:"read",async run({userId,args}){const id=String(args?.investigationId||args?.requestId||args?.id||"").trim();if(!id)throw new Error("An investigation ID is required");let artifact=await openInvestigationArtifact(userId,id);if(!artifact){const legacy=(await listDiagnosticPlans(userId,{limit:40})).find(item=>item.requestId===id);if(legacy)artifact=await persistInvestigationArtifact(userId,legacy);}if(!artifact)throw new Error(`Investigation artifact ${id} was not found in durable artifact storage or the legacy diagnostic plan store`);return investigationArtifactPage(artifact,{cursor:args?.cursor,includeRaw:Boolean(args?.includeRaw),maxBytes:args?.maxBytes})}});
defineTool({name:"sierra.investigation_report_checkpoint",workforceOnly,description:"Checkpoint delivery of one versioned investigation report section. The full report becomes delivered only after every section is accessible.",risk:"low_risk_write",async run({userId,args}){const id=String(args?.investigationId||args?.requestId||"").trim();if(!id)throw new Error("An investigation ID is required");return checkpointReportDelivery(userId,id,{sectionId:args?.sectionId,delivered:Boolean(args?.delivered)})}});
defineTool({name:"sierra.diagnostic_investigation",workforceOnly,description:"Run and durably retain one read-only cross-system Sierra investigation. Each source executes independently and the final report synthesizes coverage, freshness, contradictions, and missing evidence under a request ID.",risk:"read",async run({userId,args}){return runDurableDiagnosticPlan(userId,args||{},async(name,toolArgs)=>{const tool=registry.get(name);if(!tool)throw new Error(`Required diagnostic tool is unavailable: ${name}`);if(tool.risk!=="read")throw new Error(`Diagnostic plans cannot execute non-read tool: ${name}`);try{return{ok:true,result:await Promise.race([tool.run({userId,args:toolArgs}),new Promise((_,reject)=>setTimeout(()=>reject(new Error(`${name} exceeded its 12000ms diagnostic timeout`)),12000))])}}catch(error){return{ok:false,error:error instanceof Error?error.message:String(error)}}})}});
defineTool({name:"sierra.continue_diagnostic_investigation",workforceOnly,description:"Continue the latest durable deal investigation against one named deal or merchant. Reuse fresh evidence, execute only missing or stale read contracts, fail closed on unknown evidence, and retain the synthesized continuation under a new request ID.",risk:"read",async run({userId,args}){return continueDurableDiagnosticPlan(userId,args||{},async(name,toolArgs)=>{const tool=registry.get(name);if(!tool)throw new Error(`Required continuation tool is unavailable: ${name}`);if(tool.risk!=="read")throw new Error(`Continuation plans cannot execute non-read tool: ${name}`);try{return{ok:true,result:await Promise.race([tool.run({userId,args:toolArgs}),new Promise((_,reject)=>setTimeout(()=>reject(new Error(`${name} exceeded its 12000ms continuation timeout`)),12000))])}}catch(error){return{ok:false,error:error instanceof Error?error.message:String(error)}}})}});
defineTool({name:"sierra.exception_outreach",workforceOnly,description:"Queue Sierra's governed exception-resolution outreach for a deal. This may contact the original deal source and therefore requires external-side-effect approval.",risk:"external_side_effect",async run({userId,args}){return queueSierraAction(userId,{reference:args?.reference||args?.referenceNumber,action:"exception_outreach",reason:args?.reason})}});
defineTool({name:"sierra.lender_followup",workforceOnly,description:"Queue a governed Sierra lender follow-up for a deal. This creates an external communication and requires approval.",risk:"external_side_effect",async run({userId,args}){return queueSierraAction(userId,{reference:args?.reference||args?.referenceNumber,action:"lender_followup",reason:args?.reason})}});
defineTool({name:"sierra.refresh_pipeline",workforceOnly,description:"Queue a safe Sierra pipeline re-evaluation for a deal after new evidence or a resolved exception.",risk:"low_risk_write",async run({userId,args}){return queueSierraAction(userId,{reference:args?.reference||args?.referenceNumber,action:"refresh_pipeline",reason:args?.reason})}});
defineTool({name:"sierra.reprocess_documents",workforceOnly,description:"Queue a bounded reprocessing pass for a deal's existing application and statement evidence. It does not fabricate or replace source documents.",risk:"low_risk_write",async run({userId,args}){return queueSierraAction(userId,{reference:args?.reference||args?.referenceNumber,action:"reprocess_documents",reason:args?.reason})}});
defineTool({name:"sierra.reconcile_deal",workforceOnly,description:"Queue a bounded reconciliation of a deal across canonical CRM state, pipeline state, lender activity, offers, funding evidence, and accounting evidence.",risk:"low_risk_write",async run({userId,args}){return queueSierraAction(userId,{reference:args?.reference||args?.referenceNumber,action:"reconcile_deal",reason:args?.reason})}});
defineTool({name:"sierra.verify_lender_delivery",workforceOnly,description:"Queue verification of lender delivery and response evidence for a deal without sending a new submission.",risk:"low_risk_write",async run({userId,args}){return queueSierraAction(userId,{reference:args?.reference||args?.referenceNumber,action:"verify_lender_delivery",reason:args?.reason})}});
defineTool({name:"campaigns.smartlead",description:"Read provider-direct Smartlead campaigns and their current status. Smartlead is the campaign source of truth when connected.",risk:"read",async run(){return getSmartleadCampaigns()}});
defineTool({name:"campaigns.diagnose",description:"Diagnose Smartlead campaign state from provider-direct evidence without changing campaign status or sending.",risk:"read",async run(){return diagnoseSmartleadCampaigns()}});
defineTool({name:"campaigns.prepare_status_change",description:"Prepare a Smartlead campaign start, pause, or stop action for explicit approval. This does not change the provider.",risk:"low_risk_write",async run({userId,args}){const campaignId=String(args?.campaignId||"").trim(),status=String(args?.status||"").trim().toUpperCase();if(!/^\d+$/.test(campaignId))throw new Error("A numeric Smartlead campaign ID is required");if(!["START","PAUSED","STOPPED"].includes(status))throw new Error("Status must be START, PAUSED, or STOPPED");return createApprovalRequest(userId,{domain:"campaigns",actionType:"smartlead_campaign_status",title:`Smartlead campaign ${campaignId}: ${status}`,summary:`Prepare provider-direct ${status} for Smartlead campaign ${campaignId}. No action occurs until explicit approval.`,evidence:{campaignId,status},risk:status==="START"?"high":"medium",reversible:status!=="STOPPED",verificationMethod:"Re-read provider campaign inventory and require the requested status.",rollbackPlan:status==="START"?"Pause the same campaign if verification or safety checks fail.":"No automatic rollback; require a new approved status action."})}});
defineTool({name:"campaigns.execute_approved_status_change",description:"Execute one explicitly approved Smartlead campaign status change and verify the provider state. Requires approval ID and idempotency key.",risk:"external_side_effect",async run({userId,args}){const approval=await getApprovalRequest(userId,args?.approvalId);if(!approval||approval.status!=="approved")throw new Error("An approved campaign change request is required");if(approval.actionType!=="smartlead_campaign_status")throw new Error("Approval is not for a Smartlead campaign status change");if(!String(args?.idempotencyKey||"").trim())throw new Error("Idempotency key is required");return updateSmartleadCampaignStatus(args?.campaignId,args?.status)}});
defineTool({name:"system.vercel",description:"Read provider-direct Vercel production deployment state and recent runtime errors for Sierra.",risk:"read",async run(){return getVercelObservability()}});
defineTool({name:"system.render",description:"Read provider-direct Render deployment state and recent application/runtime errors for Georgie's backend.",risk:"read",async run(){return getRenderObservability()}});
defineTool({name:"system.github",description:"Read provider-direct GitHub repository and Actions health for Georgie without changing source or workflows.",risk:"read",async run(){return getGithubObservability()}});
defineTool({name:"system.supabase",description:"Read governed Supabase-backed Sierra infrastructure health without changing database state.",risk:"read",async run({userId}){return getSierraInfrastructure(userId)}});
defineTool({name:"system.providers",description:"Read provider-direct Vercel and Render observability together and report any connection or runtime gaps.",risk:"read",async run(){return getProviderObservability()}});
defineTool({name:"system.maintenance",description:"Read Georgie's durable maintenance state, evidence coverage, detected signals, authority mode, and verified learning outcomes.",risk:"read",async run({userId}){return maintenanceStatus(userId)}});
defineTool({name:"system.maintenance_check",description:"Run one bounded maintenance observation cycle across Sierra health, infrastructure, and deployment providers. This observes and records evidence but does not perform consequential actions.",risk:"low_risk_write",async run(){return runMaintenanceCycle()}});
defineTool({name:"system.revenue_controller",description:"Read Georgie's progressive revenue-controller phase, deal coverage, gates, and current per-deal assignments.",risk:"read",async run({userId}){return revenueControllerStatus(userId)}});
defineTool({name:"system.revenue_controller_activate",description:"Activate progressive Phase 1 deal-flow control, assign Georgie to every current Sierra deal, persist the governed revenue objective, and run the first evidence cycle. Does not send messages or submit to lenders.",risk:"low_risk_write",async run({userId}){return activateRevenueController(userId)}});
defineTool({name:"system.phase2_foundation",description:"Read the machine-readable Phase 2 engineering foundation: event contract, lifecycle state machine, CRM idempotency, readiness gates, dashboards, alerts, rollout, and regression certification. Design-only; no production mutation.",risk:"read",async run(){return phase2Foundation()}});
defineTool({name:"system.evaluations",description:"Read Georgie's measured intelligence scorecard for latency, evidence coverage, action success, and high-impact review requirements.",risk:"read",async run({userId,args}){return evaluationScorecard(userId,{limit:args?.limit||200})}});
defineTool({name:"system.resource_governor",description:"Read Georgie's live bounded-concurrency, queue-pressure, and saturation state to verify that intelligence workloads remain balanced.",risk:"read",async run(){return resourceGovernorStatus()}});
defineTool({name:"decisions.list",description:"Read the verified decision journal so Georgie can learn the user's approvals, rejections, corrections, rationale, and outcomes.",risk:"read",async run({userId,args}){return listDecisions(userId,{limit:args?.limit||30,domain:args?.domain||"all"})}});
defineTool({name:"decisions.record",description:"Record an explicit user decision, correction, rationale, verification, or outcome in the durable decision journal.",risk:"low_risk_write",async run({userId,args}){return recordDecision(userId,args||{})}});
defineTool({name:"approvals.list",description:"List pending, approved, rejected, deferred, or all governed action approvals with evidence, risk, verification, and rollback contracts.",risk:"read",async run({userId,args}){return listApprovals(userId,{status:args?.status||"pending",limit:args?.limit||25})}});
defineTool({name:"approvals.decide",description:"Record Jason's explicit approval, rejection, or deferral for one exact approval ID. This authorizes but does not execute the action.",risk:"sensitive_write",async run({userId,args}){const id=String(args?.approvalId||"").trim(),decision=String(args?.decision||"").toLowerCase();if(!id)throw new Error("Approval ID is required");return decideApproval(userId,id,{decision,note:args?.note||"Explicit decision issued through Georgie conversation"})}});
defineTool({name:"approvals.prepare_plan",description:"Save a durable, versioned, exact-scope repair or execution plan and issue its specific approval ID. The execution descriptor must name one available tool with bounded arguments plus optional verification reads. Preparing never executes.",risk:"low_risk_write",async run({userId,args}){return prepareApprovalPlan(userId,args||{})}});
defineTool({name:"approvals.plans",description:"List durable versioned repair plans, their exact approval IDs, execution state, verification evidence, and any precise missing tool.",risk:"read",async run({userId,args}){return listApprovalPlans(userId,{limit:args?.limit||25})}});
defineTool({name:"approvals.approve_plan",description:"Approve one exact plan only when the supplied approval ID is authoritatively bound to it, then atomically create its durable dispatch intent.",risk:"sensitive_write",async run({userId,args}){const approved=await approvePlanById(userId,args||{});const dispatch=await dispatchApprovedPlansNow(userId);return{...approved,dispatch}}});
defineTool({name:"approvals.continue_latest",description:"Resolve explicit conversational approval such as 'complete it, you have my approval' to the latest eligible versioned plan, validate every required tool, execute only its exact bound descriptor, verify it, and durably report the outcome. Never invents a queue.",risk:"low_risk_write",async run({userId,args}){
  const resolved=await resolveConversationalApproval(userId,args?.utterance||"",{sessionId:args?.sessionId||"native"});
  if(!resolved?.ok)return resolved||{ok:false,status:"not_an_approval",error:"The utterance was not explicit approval."};
  const preflight=preflightExecution(resolved.execution,listToolDefinitions());
  if(!preflight.ok){await transitionApprovalPlan(userId,resolved.plan.id,{status:"blocked_missing_tool",error:preflight.reason,missingTool:preflight.missingTool});return{ok:false,status:"blocked_missing_tool",approvalId:resolved.approval.id,planId:resolved.plan.id,version:resolved.plan.version,missingTool:preflight.missingTool,error:preflight.reason};}
  const target=registry.get(resolved.execution.tool);if(!target){const missingTool=resolved.execution.tool;await transitionApprovalPlan(userId,resolved.plan.id,{status:"blocked_missing_tool",missingTool,error:`Required tool ${missingTool} is unavailable.`});return{ok:false,status:"blocked_missing_tool",missingTool,error:`Required tool ${missingTool} is unavailable.`};}
  await transitionApprovalPlan(userId,resolved.plan.id,{status:"executing"});
  try{
    const governance={approvalId:resolved.approval.id,planId:resolved.plan.id,idempotencyKey:resolved.plan.dispatch?.idempotencyKey||`approval:${resolved.approval.id}:plan:${resolved.plan.id}`};
    await recordApprovalDispatch(userId,resolved.plan.id,{status:"dispatching"});
    const result=await target.run({userId,args:{...(resolved.execution.args||{}),_governance:governance}});
    const dispatchReceipt=result?.dispatchReceipt||null;
    if(resolved.execution.tool.startsWith("mac.")&&!dispatchReceipt)throw new Error("Approved Mac execution did not produce a durable dispatch receipt");
    await recordApprovalDispatch(userId,resolved.plan.id,{status:"accepted",receipt:dispatchReceipt||{acceptedAt:new Date().toISOString(),tool:resolved.execution.tool}});
    const verification=[];for(const check of resolved.execution.verification||[]){const verifyTool=registry.get(check.tool);if(!verifyTool){verification.push({ok:false,accepted:false,state:"UNKNOWN",tool:check.tool,error:`Required verification tool ${check.tool} is unavailable.`});continue;}try{const verificationResult=await verifyTool.run({userId,args:check.args||{}});const semantic=verifyBusinessOutcome(check.tool,verificationResult,{expect:check.expect});verification.push({ok:true,tool:check.tool,result:verificationResult,...semantic});}catch(error){verification.push({ok:false,accepted:false,state:"UNKNOWN",tool:check.tool,error:error instanceof Error?error.message:String(error)});}}
    const nonTerminalStatuses=new Set(['queued','pending','accepted','running','in_progress']);
    const resultStatus=String(result?.status||'').toLowerCase();
    const nestedStatuses=Array.isArray(result?.lanes)?result.lanes.map(item=>String(item?.status||'').toLowerCase()):[];
    const terminal=!nonTerminalStatuses.has(resultStatus)&&!nestedStatuses.some(status=>nonTerminalStatuses.has(status));
    const executionSemantic=verifyBusinessOutcome(resolved.execution.tool,result,{expect:resolved.execution.expect});
    const verificationSatisfied=verification.length>0?verification.every(item=>item.ok&&item.accepted):resolved.execution.tool==="mac.browser_workflow"&&executionSemantic.accepted;
    const verified=terminal&&executionSemantic.accepted&&verificationSatisfied;
    const status=verified?"verified":terminal?"blocked_incomplete_evidence":"verification_pending";
    await transitionApprovalPlan(userId,resolved.plan.id,{status,executionResult:result,verification});
    return{ok:verified,status,approvalId:resolved.approval.id,planId:resolved.plan.id,version:resolved.plan.version,executedTool:resolved.execution.tool,result,executionVerification:executionSemantic,verification};
  }catch(error){const message=error instanceof Error?error.message:String(error);await recordApprovalDispatch(userId,resolved.plan.id,{status:"retry_wait",error:message});await transitionApprovalPlan(userId,resolved.plan.id,{status:"approved_dispatch_retry",error:message});return{ok:false,status:"approved_dispatch_retry",approvalId:resolved.approval.id,planId:resolved.plan.id,version:resolved.plan.version,executedTool:resolved.execution.tool,error:message};}
}});
defineTool({name:"system.status",description:"Inspect Georgie's live capability manifest, connection states, verification paths, platform constraints, and resource balance without exposing credentials.",risk:"read",async run(){return getCapabilityManifest()}});
defineTool({name:"coordination.mission",description:"Read the permanent shared mission, priority order, authority boundaries, and background engineering status used by Jason, Georgie, and authorized engineering assistants.",risk:"read",async run({userId}){return Promise.all([missionStatus(userId),engineeringCoordinatorStatus(userId)]).then(([mission,coordinator])=>({mission:mission.mission,coordinator}))}});
defineTool({name:"coordination.handoffs",description:"List durable technical handoffs shared between Jason, Georgie, and authorized engineering assistants, including status, lease, attempts, evidence, and next gate.",risk:"read",async run({userId,args}){return listHandoffs(userId,args||{})}});
defineTool({name:"coordination.handoff.create",description:"Create one durable, idempotent engineering handoff with objective, acceptance criteria, evidence, priority, and authority scope. This records work; it does not silently expand mutation authority.",risk:"low_risk_write",async run({userId,args}){return enqueueHandoff(userId,args||{})}});
defineTool({name:"coordination.seed_mission",description:"Seed Georgie's permanent Sierra engineering mission into the durable handoff queue without duplicating existing work.",risk:"low_risk_write",async run({userId}){return seedMissionWork(userId)}});
defineTool({name:"coordination.run_cycle",description:"Run one bounded background engineering cycle: claim one durable handoff, gather evidence or execute only a pre-certified reversible repair, persist the outcome, and retry temporary failures.",risk:"low_risk_write",async run({userId}){return runEngineeringCoordinatorCycle(userId)}});
defineTool({name:"coordination.repair_authority",description:"Evaluate whether a proposed code repair qualifies only for an automatic isolated-branch commit after passing tests, rollback, scope, and protected-file checks. Never authorizes merge or deployment.",risk:"read",async run({args}){return autonomousRepairPolicy(args||{})}});
defineTool({name:"task.elite_analyze",description:"Turn any unfamiliar, complex, personal, business, technical, creative, research, or high-stakes objective into a deterministic task contract with domains, risks, authority, reasoning tier, workflow, evidence requirements, and completion rules.",risk:"read",async run({args}){return eliteTaskContract(args||{})}});
defineTool({name:"task.elite_start",description:"Persist a complex objective as one durable elite-task handoff with the correct authority boundary and evidence contract. This records and coordinates work; it never treats queueing as completion.",risk:"low_risk_write",async run({userId,args}){return startEliteTask(userId,args||{})}});
defineTool({name:"task.elite_verify",description:"Verify a task outcome against its acceptance criteria, authoritative evidence, action receipts, quarantine status, and learning eligibility.",risk:"read",async run({args}){return verifyEliteTask(eliteTaskContract(args?.contract||args||{}),args?.outcome||{})}});
defineTool({name:"system.action_journal",description:"Read Georgie's durable journal of governed tool attempts, approval requirements, outcomes, and failures.",risk:"read",async run({userId,args}){return listActionJournal(userId,{limit:args?.limit||50})}});
defineTool({name:"system.reconciliation_status",description:"Read the durable state of Georgie's scheduled intake-transfer, missing-date, funding-evidence, and health-reconciliation workers.",risk:"read",async run({userId}){return reconciliationStatus(userId)}});
defineTool({name:"system.reconciliation_check",description:"Run one bounded scheduled-reconciliation cycle. Shadow mode only observes; bounded mode queues idempotent Sierra workforce actions.",risk:"low_risk_write",async run(){return runReconciliationCycle()}});
defineTool({name:"system.reconciliation_execute_bounded",description:"Execute one explicitly approved bounded reconciliation cycle across the exact Sierra lanes in the approved plan. The automation kill switch still overrides execution.",risk:"sensitive_write",async run({userId}){return runReconciliationCycle({requestedMode:"bounded",userId})}});
defineTool({name:"system.world_state",description:"Read Georgie's compact cross-session world state: active commitments, unresolved events, pending approvals, recent decisions, active specialization packs, and governing boundaries.",risk:"read",async run({userId,args}){return buildWorldState(userId,args?.context||"",{domain:args?.domain||"general"})}});
defineTool({name:"system.continuity",description:"Read Georgie's durable objective graph, unfinished engineering and execution work, recoverable Mac jobs, and ranked next actions across sessions.",risk:"read",async run({userId,args}){return operatingContinuity(userId,{limit:args?.limit||50})}});
defineTool({name:"system.objective_upsert",description:"Create or update a durable objective, commitment, engineering effort, investigation, execution, or follow-up. This records operating intent but performs no external action.",risk:"low_risk_write",async run({userId,args}){return upsertOperatingNode(userId,args||{})}});
defineTool({name:"system.objective_transition",description:"Advance a durable operating node through planned, active, waiting, blocked, recovering, verified, or cancelled state with verification and recovery evidence. This does not perform the underlying external action.",risk:"low_risk_write",async run({userId,args}){return transitionOperatingNode(userId,args?.nodeId,args||{})}});
defineTool({name:"system.domain_packs",description:"List Georgie's universal core and installed specialization packs without mixing their credentials or authority boundaries.",risk:"read",async run(){return listDomainPacks()}});
defineTool({name:"system.world_state_snapshot",description:"Read Georgie's continuously refreshed durable world-state snapshot without rebuilding it inside the current turn.",risk:"read",async run({userId}){return readWorldStateSnapshot(userId)}});
defineTool({name:"system.world_state_refresh",description:"Refresh Georgie's universal world-state snapshot from current tasks, events, approvals, and decisions.",risk:"low_risk_write",async run({userId}){return refreshWorldState(userId)}});
defineTool({name:"system.intelligence_benchmark",description:"Run Georgie's deterministic multi-domain routing, tool-selection, cost-policy, and latency-target benchmark specification.",risk:"read",async run(){return runStaticBenchmark()}});
defineTool({name:"system.self_evolution",description:"Read Georgie's governed continuous-improvement state, research policy, measured capability gaps, proposals, and promotion gates.",risk:"read",async run({userId}){return selfEvolutionStatus(userId)}});
defineTool({name:"system.self_evolution_check",description:"Run one bounded improvement cycle: measure Georgie's scorecard and benchmark, identify capability gaps, and persist testable proposals. It cannot modify code, credentials, deployments, or consequential business records.",risk:"low_risk_write",async run({userId}){return runSelfEvolutionCycle(userId)}});
defineTool({name:"system.background_operations",description:"Read Georgie's durable Phase 1 background operating state, notification policy, incidents, deliveries, cycle history, and kill-switch observation.",risk:"read",async run({userId}){return backgroundOperatingStatus(userId)}});
defineTool({name:"system.background_operations_activate",description:"Activate Phase 1 observe-and-notify operation and run its first revenue-chain cycle. External business actions and production mutations remain gated.",risk:"low_risk_write",async run({userId}){return activateBackgroundOperatingLayer(userId)}});
defineTool({name:"system.background_operations_check",description:"Run one durable observe-only revenue-chain monitoring cycle, record incidents, notify under the approved escalation policy, and verify provider acceptance.",risk:"low_risk_write",async run({userId}){return runBackgroundOperatingCycle(userId)}});
defineTool({name:"system.intelligence_control_map",description:"Read Georgie's durable authoritative inventory of Sierra systems, revenue handoffs, ownership, connector verification, authority, approvals, gaps, incidents, revenue dependencies, escalation, recovery, and kill-switch coverage.",risk:"read",async run({userId}){return intelligenceControlMapStatus(userId)}});
defineTool({name:"system.intelligence_control_map_refresh",description:"Refresh Georgie's durable Intelligence and Control Map from current provider evidence and durable operating state. Read-only against business systems; writes only the versioned map snapshot.",risk:"low_risk_write",async run({userId}){return refreshIntelligenceControlMap(userId)}});
defineTool({name:"system.create_enrollment_code",description:"Create a cryptographically random, single-use Georgie device enrollment code that expires after 15 minutes. Only run after the authenticated user explicitly requests a code.",risk:"sensitive_write",async run(){return createEnrollmentCode()}});
export function listToolDefinitions({workforce=sierraWorkforceConfigured(),includeUnavailable=true}={}){return[...registry.values()].filter(tool=>includeUnavailable||workforce||!tool.workforceOnly).map(({name,description,risk,workforceOnly})=>({name,description,risk,attached:true,configured:workforceOnly?Boolean(workforce):true,precondition:workforceOnly&&!workforce?"secure_sierra_workforce_configuration":null}))}
export function persistentToolSurface(options={}){const tools=listToolDefinitions({...options,includeUnavailable:true});return{generatedAt:new Date().toISOString(),mode:"persistent_governed_registry",attachedToEveryTurn:true,registeredToolCount:tools.length,configuredToolCount:tools.filter(tool=>tool.configured!==false).length,tools};}
export function canAutoExecute(risk,policy="low_risk_write"){return LEVELS[risk]<=LEVELS[policy]}
export async function executeTool({name,args,userId,policy="low_risk_write",workforce=sierraWorkforceConfigured()}){const startedAt=new Date().toISOString(),tool=registry.get(name);let outcome;if(!tool)outcome={ok:false,tool:name,missingCapability:name,error:`Required governed tool is not registered: ${name}`};else if(process.env.GEORGIE_AUTOMATION_KILL_SWITCH==="true"&&tool.risk!=="read")outcome={ok:false,tool:name,risk:tool.risk,blockedBy:"automation_kill_switch",error:"Georgie automation kill switch is active"};else if(tool.workforceOnly&&!workforce)outcome={ok:false,tool:name,risk:tool.risk,attached:true,blockedBy:"secure_sierra_workforce_configuration",missingCapability:"secure_sierra_workforce_configuration",error:`Tool ${name} is attached, but secure Sierra workforce configuration is not live in this runtime`};else if(!canAutoExecute(tool.risk,policy))outcome={ok:false,approvalRequired:true,tool:name,risk:tool.risk,args,blockedBy:"approval_policy"};else try{outcome={ok:true,tool:name,risk:tool.risk,result:await tool.run({userId,args})}}catch(error){outcome={ok:false,tool:name,risk:tool.risk,attached:true,blockedBy:"runtime_execution_failure",error:error instanceof Error?error.message:"Tool execution failed"};}void recordAction(userId,{tool:name,risk:tool?.risk,status:outcome.ok?"completed":outcome.approvalRequired?"approval_required":"failed",approvalRequired:outcome.approvalRequired,argsSummary:args&&typeof args==="object"?args:{},error:outcome.error,startedAt}).catch(error=>console.warn("Action journal persistence delayed:",error instanceof Error?error.message:error));return outcome;}

let approvalDispatchTimer=null,approvalDispatchBusy=false,approvalDispatchRequested=false;
const APPROVAL_DISPATCH_RECOVERY_INTERVAL_MS=Math.max(30_000,Math.min(300_000,Number(process.env.GEORGIE_APPROVAL_DISPATCH_RECOVERY_MS||30_000)));
export function approvalDispatchPolicy(){return{mode:"event_driven_with_recovery_sweep",approvalPath:"immediate",idleCloudPolling:false,recoveryIntervalMs:APPROVAL_DISPATCH_RECOVERY_INTERVAL_MS,coalesced:true,idempotent:true}}
async function runApprovalDispatchSweep(userId=process.env.GEORGIE_PRIMARY_USER_ID||"primary"){
  if(approvalDispatchBusy){approvalDispatchRequested=true;return{coalesced:true,dispatched:[]}}
  approvalDispatchBusy=true;const dispatched=[];
  try{
    do{
      approvalDispatchRequested=false;
      for(const plan of await listRecoverableApprovalDispatches(userId,{limit:10})){
        if(!String(plan.execution?.tool||"").startsWith("mac."))continue;
        const target=registry.get(plan.execution.tool);if(!target)continue;
        await recordApprovalDispatch(userId,plan.id,{status:"dispatching"});
        try{
          const result=await target.run({userId,args:{...(plan.execution.args||{}),_governance:{approvalId:plan.approvalId,planId:plan.id,idempotencyKey:plan.dispatch.idempotencyKey}}});
          if(!result?.dispatchReceipt)throw new Error("Approved Mac execution did not produce a durable dispatch receipt");
          await recordApprovalDispatch(userId,plan.id,{status:"accepted",receipt:result.dispatchReceipt});
          dispatched.push({planId:plan.id,approvalId:plan.approvalId,status:"accepted",dispatchReceipt:result.dispatchReceipt});
        }catch(error){
          const message=error instanceof Error?error.message:String(error);
          await recordApprovalDispatch(userId,plan.id,{status:"retry_wait",error:message,retryDelayMs:Math.min(30_000,1000*2**Math.min(Number(plan.dispatch?.attempts||0),5))});
          dispatched.push({planId:plan.id,approvalId:plan.approvalId,status:"retry_wait",error:message});
        }
      }
    }while(approvalDispatchRequested);
    return{coalesced:false,dispatched};
  }finally{approvalDispatchBusy=false}
}
export async function dispatchApprovedPlansNow(userId){return runApprovalDispatchSweep(userId)}
export function startApprovalDispatchWorker(){
  if(approvalDispatchTimer)return approvalDispatchTimer;
  const userId=process.env.GEORGIE_PRIMARY_USER_ID||"primary";
  approvalDispatchTimer=setInterval(()=>void runApprovalDispatchSweep(userId).catch(error=>console.warn("Approval dispatch recovery delayed:",error instanceof Error?error.message:error)),APPROVAL_DISPATCH_RECOVERY_INTERVAL_MS);
  approvalDispatchTimer.unref?.();
  void runApprovalDispatchSweep(userId).catch(error=>console.warn("Approval dispatch startup recovery delayed:",error instanceof Error?error.message:error));
  return approvalDispatchTimer;
}
