import { searchMemories } from "./memory.js";
import { createTask, listTasks, updateTask } from "./tasks.js";
import { enqueueMacJob, listMacJobs } from "./mac/queue.js";
import { listNeoMailboxes, listRecentMessages, neoMailConfigured, readMessage, searchMessages, sendMessage, verifyNeoMailbox } from "./integrations/neo-mail.js";
import { getSierraDeal, getSierraHealth, getSierraInfrastructure, getSierraLenderResponses, getSierraNetworkGaps, getSierraOffers, getSierraPortfolio, getSierraStrategy, queueSierraAction, sierraWorkforceConfigured } from "./integrations/sierra-workforce.js";
import { getProviderObservability, getRenderObservability, getVercelObservability, renderObservabilityConfigured, vercelObservabilityConfigured } from "./integrations/provider-observability.js";
import { maintenanceStatus, runMaintenanceCycle } from "./maintenance-sentinel.js";

const LEVELS={read:0,low_risk_write:1,sensitive_write:2,external_side_effect:3};const registry=new Map();function defineTool(definition){registry.set(definition.name,definition)}
defineTool({name:"memory.search",description:"Search Georgie's durable memory for relevant user context.",risk:"read",async run({userId,args}){return searchMemories(userId,String(args?.query||""),Number(args?.limit||8))}});
defineTool({name:"tasks.list",description:"List the user's open, completed, or all tasks.",risk:"read",async run({userId,args}){return listTasks(userId,{status:args?.status||"open",limit:args?.limit||30})}});
defineTool({name:"tasks.create",description:"Create a task for the user.",risk:"low_risk_write",async run({userId,args}){return createTask({userId,...(args||{}),source:"georgie-tool"})}});
defineTool({name:"tasks.update",description:"Update, complete, or cancel a task.",risk:"low_risk_write",async run({userId,args}){return updateTask(userId,args?.taskId,args?.patch||{})}});
function queueMac(userId,args,action,risk,reason,payload={}){return enqueueMacJob({userId,deviceId:args?.deviceId||"primary-mac",action,args:payload,risk,reason})}
defineTool({name:"mac.jobs",description:"List recent jobs executed or queued for the user's Georgie Mac Agent.",risk:"read",async run({userId,args}){return listMacJobs(userId,Number(args?.limit||30))}});
defineTool({name:"mac.system_info",description:"Ask the connected Mac for hostname, architecture, OS release and uptime.",risk:"read",async run({userId,args}){return queueMac(userId,args,"system.info","read","System status requested by Georgie")}});
defineTool({name:"mac.clipboard_read",description:"Read text currently on the connected Mac clipboard.",risk:"read",async run({userId,args}){return queueMac(userId,args,"clipboard.read","read","Clipboard requested by Georgie")}});
defineTool({name:"mac.file_read",description:"Read a text file from the connected Mac Desktop, Documents, or Downloads folder.",risk:"read",async run({userId,args}){return queueMac(userId,args,"file.read","read","File requested by Georgie",{path:args?.path})}});
defineTool({name:"mac.open_app",description:"Open an allowlisted application on the connected Mac.",risk:"low_risk_write",async run({userId,args}){return queueMac(userId,args,"app.open","low_risk_write","Application launch requested by Georgie",{app:args?.app})}});
defineTool({name:"mac.activate_app",description:"Bring an allowlisted application to the foreground on the connected Mac.",risk:"low_risk_write",async run({userId,args}){return queueMac(userId,args,"app.activate","low_risk_write","Application activation requested by Georgie",{app:args?.app})}});
defineTool({name:"mac.open_url",description:"Open an HTTP or HTTPS URL on the connected Mac.",risk:"low_risk_write",async run({userId,args}){return queueMac(userId,args,"url.open","low_risk_write","Web page requested by Georgie",{url:args?.url})}});
defineTool({name:"mac.clipboard_write",description:"Put text onto the connected Mac clipboard.",risk:"low_risk_write",async run({userId,args}){return queueMac(userId,args,"clipboard.write","low_risk_write","Clipboard update requested by Georgie",{text:args?.text})}});
defineTool({name:"mac.notification",description:"Show a local notification on the connected Mac.",risk:"low_risk_write",async run({userId,args}){return queueMac(userId,args,"notification.show","low_risk_write","Notification requested by Georgie",{title:args?.title,body:args?.body})}});
defineTool({name:"mac.screen_capture",description:"Capture the connected Mac's current screen for visual understanding. Requires sensitive authorization because the screen may contain private information.",risk:"sensitive_write",async run({userId,args}){return queueMac(userId,args,"screen.capture","sensitive_write","Screen capture requested by Georgie")}});
defineTool({name:"mac.type_text",description:"Type text into the currently focused Mac application. Requires sensitive authorization because it changes application state.",risk:"sensitive_write",async run({userId,args}){return queueMac(userId,args,"ui.type_text","sensitive_write","UI text entry requested by Georgie",{text:args?.text})}});
defineTool({name:"mac.key",description:"Send an allowlisted navigation or editing key to the currently focused Mac application, optionally with command/option/control/shift modifiers.",risk:"sensitive_write",async run({userId,args}){return queueMac(userId,args,"ui.key","sensitive_write","UI key command requested by Georgie",{key:args?.key,modifiers:args?.modifiers})}});
defineTool({name:"email.accounts",description:"List the user's configured Neo Mail mailboxes and their business roles.",risk:"read",async run(){return listNeoMailboxes()}});
defineTool({name:"email.verify",description:"Verify secure IMAP and SMTP connectivity for a configured Neo Mail mailbox.",risk:"read",async run({args}){return verifyNeoMailbox(args?.mailboxId)}});
defineTool({name:"email.list",description:"List recent Neo Mail inbox messages. Supports unseen-only filtering.",risk:"read",async run({args}){return listRecentMessages(args?.mailboxId,{limit:args?.limit||20,unseenOnly:Boolean(args?.unseenOnly)})}});
defineTool({name:"email.search",description:"Search a Neo Mail mailbox by sender, recipient, subject, or message body.",risk:"read",async run({args}){return searchMessages(args?.mailboxId,{query:args?.query||"",limit:args?.limit||25})}});
defineTool({name:"email.read",description:"Read the content and attachment metadata for one Neo Mail message.",risk:"read",async run({args}){return readMessage(args?.mailboxId,args?.uid,{markSeen:Boolean(args?.markSeen)})}});
defineTool({name:"email.send",description:"Send an email through a configured Neo Mail mailbox. This creates an external communication and requires external-side-effect authorization.",risk:"external_side_effect",async run({args}){return sendMessage(args?.mailboxId,{to:args?.to,cc:args?.cc,bcc:args?.bcc,subject:args?.subject,text:args?.text,html:args?.html,replyTo:args?.replyTo})}});
const workforceOnly=true;
defineTool({name:"sierra.portfolio",workforceOnly,description:"Read Sierra's canonical CRM portfolio, prioritized by operational attention, including pipeline, underwriting, evidence, exceptions, lender activity, offers and closing status.",risk:"read",async run({userId,args}){return getSierraPortfolio(userId,{limit:args?.limit||25})}});
defineTool({name:"sierra.deal",workforceOnly,description:"Read the complete canonical Sierra CRM workspace for one deal by SCA reference number or referral ID.",risk:"read",async run({userId,args}){return getSierraDeal(userId,args?.reference||args?.referenceNumber||args?.id)}});
defineTool({name:"sierra.health",workforceOnly,description:"Read Sierra's latest operations-health snapshot including pipeline failures, lender delivery, evidence and recovery status.",risk:"read",async run({userId}){return getSierraHealth(userId)}});
defineTool({name:"sierra.infrastructure",workforceOnly,description:"Read Sierra's governed infrastructure, auth, worker and integration health: recovery cron spine, automation backlog, invariant violations, failed pipeline stages, correspondence leases, dead-letter recovery, management-query pressure, CapitalApply fast-path health, aggregate auth activity, worker queues and registered connection status.",risk:"read",async run({userId}){return getSierraInfrastructure(userId)}});
defineTool({name:"sierra.strategy",workforceOnly,description:"Read Sierra's prioritized company-evolution and strategic intelligence recommendations, ranked by impact, evidence, confidence, effort and risk.",risk:"read",async run({userId}){return getSierraStrategy(userId)}});
defineTool({name:"sierra.network_gaps",workforceOnly,description:"Read financing-product gaps in Sierra's lender network plus verified external lender candidates and partnership-outreach status.",risk:"read",async run({userId}){return getSierraNetworkGaps(userId)}});
defineTool({name:"sierra.lenders",workforceOnly,description:"Read lender placements, response timing, follow-up state, requests and communication activity for a Sierra deal.",risk:"read",async run({userId,args}){return getSierraLenderResponses(userId,args?.reference||args?.referenceNumber)}});
defineTool({name:"sierra.offers",workforceOnly,description:"Read and compare normalized financing offers for a Sierra deal, including payment burden, net proceeds, economics confidence and ranking.",risk:"read",async run({userId,args}){return getSierraOffers(userId,args?.reference||args?.referenceNumber)}});
defineTool({name:"sierra.exception_outreach",workforceOnly,description:"Queue Sierra's governed exception-resolution outreach for a deal. This may contact the original deal source and therefore requires external-side-effect approval.",risk:"external_side_effect",async run({userId,args}){return queueSierraAction(userId,{reference:args?.reference||args?.referenceNumber,action:"exception_outreach",reason:args?.reason})}});
defineTool({name:"sierra.lender_followup",workforceOnly,description:"Queue a governed Sierra lender follow-up for a deal. This creates an external communication and requires approval.",risk:"external_side_effect",async run({userId,args}){return queueSierraAction(userId,{reference:args?.reference||args?.referenceNumber,action:"lender_followup",reason:args?.reason})}});
defineTool({name:"sierra.refresh_pipeline",workforceOnly,description:"Queue a safe Sierra pipeline re-evaluation for a deal after new evidence or a resolved exception.",risk:"low_risk_write",async run({userId,args}){return queueSierraAction(userId,{reference:args?.reference||args?.referenceNumber,action:"refresh_pipeline",reason:args?.reason})}});
defineTool({name:"system.vercel",description:"Read provider-direct Vercel production deployment state and recent runtime errors for Sierra.",risk:"read",async run(){return getVercelObservability()}});
defineTool({name:"system.render",description:"Read provider-direct Render deployment state and recent application/runtime errors for Georgie's backend.",risk:"read",async run(){return getRenderObservability()}});
defineTool({name:"system.providers",description:"Read provider-direct Vercel and Render observability together and report any connection or runtime gaps.",risk:"read",async run(){return getProviderObservability()}});
defineTool({name:"system.maintenance",description:"Read Georgie's durable maintenance state, evidence coverage, detected signals, authority mode, and verified learning outcomes.",risk:"read",async run({userId}){return maintenanceStatus(userId)}});
defineTool({name:"system.maintenance_check",description:"Run one bounded maintenance observation cycle across Sierra health, infrastructure, and deployment providers. This observes and records evidence but does not perform consequential actions.",risk:"low_risk_write",async run(){return runMaintenanceCycle()}});
defineTool({name:"system.status",description:"Inspect currently configured Georgie capabilities.",risk:"read",async run(){return{voice:true,memory:true,handsFree:true,tasks:true,proactive:true,macAgent:Boolean(process.env.GEORGIE_MAC_AGENT_TOKEN),externalConnectors:{neoMail:neoMailConfigured(),sierraWorkforce:sierraWorkforceConfigured(),vercelObservability:vercelObservabilityConfigured(),renderObservability:renderObservabilityConfigured(),calendar:Boolean(process.env.GEORGIE_CALENDAR_ENABLED==="true"),web:Boolean(process.env.GEORGIE_WEB_ENABLED==="true"),notifications:Boolean(process.env.GEORGIE_NOTIFICATIONS_ENABLED==="true")}}}});
export function listToolDefinitions({workforce=sierraWorkforceConfigured()}={}){return[...registry.values()].filter(tool=>workforce||!tool.workforceOnly).map(({name,description,risk})=>({name,description,risk}))}
export function canAutoExecute(risk,policy="low_risk_write"){return LEVELS[risk]<=LEVELS[policy]}
export async function executeTool({name,args,userId,policy="low_risk_write",workforce=sierraWorkforceConfigured()}){const tool=registry.get(name);if(!tool)return{ok:false,error:`Unknown tool: ${name}`};if(tool.workforceOnly&&!workforce)return{ok:false,tool:name,error:"Secure Sierra workforce authorization required"};if(!canAutoExecute(tool.risk,policy))return{ok:false,approvalRequired:true,tool:name,risk:tool.risk,args};try{return{ok:true,tool:name,risk:tool.risk,result:await tool.run({userId,args})}}catch(error){return{ok:false,tool:name,error:error instanceof Error?error.message:"Tool execution failed"}}}
