-- Durable, fail-closed financing recovery slice. Service-role access only.
create table if not exists georgie_recovery_candidates(id uuid primary key default gen_random_uuid(), applicant_id text not null, deal_id text not null unique, thread_id text not null unique, lane text not null check(lane in ('historical','new')), source_application_id text not null unique, email text not null, payload jsonb not null, state text not null default 'eligible', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists georgie_recovery_suppressions(id uuid primary key default gen_random_uuid(), applicant_id text, email text, reason text not null check(reason in ('opt_out','complaint','invalid','bounce','dispute','duplicate','active_deal','recent_contact')), evidence_id text not null, expires_at timestamptz, created_at timestamptz not null default now());
create table if not exists georgie_recovery_intents(id uuid primary key default gen_random_uuid(), deal_id text not null references georgie_recovery_candidates(deal_id), applicant_id text not null, thread_id text not null, kind text not null, idempotency_key text not null unique, payload jsonb not null, status text not null default 'pending', attempts int not null default 0 check(attempts<=3), available_at timestamptz not null default now(), lease_token uuid, lease_expires_at timestamptz, provider_evidence jsonb, created_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists georgie_recovery_audit(id bigserial primary key, deal_id text not null, event_type text not null, evidence_ids text[] not null default '{}', payload jsonb not null default '{}', created_at timestamptz not null default now());
create index if not exists georgie_recovery_intents_claim on georgie_recovery_intents(status,available_at,lease_expires_at);
create index if not exists georgie_recovery_suppressions_identity on georgie_recovery_suppressions(email,applicant_id);
alter table georgie_recovery_candidates enable row level security; alter table georgie_recovery_suppressions enable row level security; alter table georgie_recovery_intents enable row level security; alter table georgie_recovery_audit enable row level security;
create or replace function georgie_claim_recovery_intents(p_limit int default 10,p_lease_seconds int default 60) returns setof georgie_recovery_intents language plpgsql security definer set search_path=public as $$ begin return query update georgie_recovery_intents i set lease_token=gen_random_uuid(),lease_expires_at=now()+make_interval(secs=>least(greatest(p_lease_seconds,10),300)),attempts=i.attempts+1,status='processing' where i.id in(select id from georgie_recovery_intents where status in('pending','retry','processing') and available_at<=now() and (lease_expires_at is null or lease_expires_at<now()) and attempts<3 order by created_at for update skip locked limit least(greatest(p_limit,1),50)) returning i.*; end $$;
create or replace function georgie_recovery_suppression(p_intent_id uuid) returns jsonb language sql security definer set search_path=public as $$ select case when exists(select 1 from georgie_recovery_intents i join georgie_recovery_candidates c on c.deal_id=i.deal_id join georgie_recovery_suppressions s on (s.email=c.email or s.applicant_id=c.applicant_id) where i.id=p_intent_id and (s.expires_at is null or s.expires_at>now())) then jsonb_build_object('allowed',false,'reason','global_suppression') when exists(select 1 from georgie_recovery_intents i join georgie_recovery_audit a on a.deal_id=i.deal_id where i.id=p_intent_id and a.event_type='provider.sent' and a.created_at>now()-interval '7 days') then jsonb_build_object('allowed',false,'reason','contact_frequency') else jsonb_build_object('allowed',true) end $$;
create or replace function georgie_complete_recovery_intent(p_id uuid,p_lease uuid,p_status text,p_evidence jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare row georgie_recovery_intents; begin if p_status not in('held','suppressed','failed','sent','completed','retry') then raise exception 'INVALID_TERMINAL_STATUS'; end if; update georgie_recovery_intents set status=p_status,provider_evidence=p_evidence,completed_at=case when p_status='retry' then null else now() end,lease_expires_at=null where id=p_id and lease_token=p_lease and status='processing' returning * into row; if row.id is null then raise exception 'LEASE_FENCED'; end if; if p_status='sent' and not (p_evidence#>>'{receipt,messageId}' is not null) then raise exception 'PROVIDER_RECEIPT_REQUIRED'; end if; insert into georgie_recovery_audit(deal_id,event_type,payload) values(row.deal_id,case when p_status='sent' then 'provider.sent' else 'intent.'||p_status end,p_evidence); return jsonb_build_object('ok',true,'status',p_status,'intentId',p_id); end $$;
revoke all on function georgie_claim_recovery_intents(int,int),georgie_recovery_suppression(uuid),georgie_complete_recovery_intent(uuid,uuid,text,jsonb) from public,anon,authenticated;
grant execute on function georgie_claim_recovery_intents(int,int),georgie_recovery_suppression(uuid),georgie_complete_recovery_intent(uuid,uuid,text,jsonb) to service_role;
